// Generates the Class 10 review-bundle artefacts: subject crosswalks, the
// outcome/atom matrix, the question-depth and reassessment matrix, the gap
// register and the machine-readable crosswalk. Read-only; deterministic.
//   bun run scripts/compliance/bundle.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { analyse, ROOT } from "./analysis";
import { VALIDATOR_VERSION, requiredVerifiedPerUnit } from "../../src/lib/compliance-shared";

const { snapshot, sourceIssues, subjects, overall } = analyse();
const stamp = new Date().toISOString().slice(0, 10);
const head = (title: string) =>
  [
    `# ${title}`,
    "",
    `**Generated:** ${stamp} · **Validator:** ${VALIDATOR_VERSION} · **Session:** ${snapshot.board} Class ${snapshot.classLevel} ${snapshot.academicYear} · **Overall status:** ${overall}`,
    "",
    "Generated by `scripts/compliance/bundle.ts`. Do not edit by hand.",
    "",
  ];

// ---------------------------------------------------------------- crosswalks
for (const s of subjects) {
  const L = head(`EduOS — CBSE Class 10 ${s.subject} Crosswalk (${snapshot.academicYear})`);
  L.push(`**Subject status:** ${s.status} · failing checks: ${s.gaps}`, "");
  L.push("## 1. Official unit → platform unit", "");
  L.push("| Official ref | Official unit | Marks | Platform unit | Platform unit id | Outcomes | Verified | Required | Verdict |");
  L.push("|---|---|---|---|---|---|---|---|---|");
  for (const c of s.crosswalk) {
    const verdict = !c.mappedUnitId ? "MISSING" : c.verified >= c.required ? "OK" : "SHORTFALL";
    L.push(`| ${c.officialRef} | ${c.officialTitle} | ${c.marks} | ${c.mappedTitle ?? "—"} | ${c.mappedUnitId ?? "—"} | ${c.outcomes} | ${c.verified} | ${c.required} | ${verdict} |`);
  }
  L.push("", "## 2. Official chapter → platform chapter", "");
  L.push("| Official ref | Chapter | Parent unit | Mapped |");
  L.push("|---|---|---|---|");
  for (const c of s.crosswalk) for (const ch of c.chapters) L.push(`| ${ch.ref} | ${ch.title} | ${c.officialTitle} | ${ch.mapped ? "yes" : "NO"} |`);
  L.push("", "## 3. Unmapped official elements", "");
  if (s.unmappedOfficialTopics.length) for (const t of s.unmappedOfficialTopics) L.push(`- ${t}`);
  else L.push("- none");
  L.push("", "## 4. Active platform units without an official mapping", "");
  if (s.outOfSyllabusUnits.length) for (const u of s.outOfSyllabusUnits) L.push(`- ${u}`);
  else L.push("- none");
  L.push("");
  writeFileSync(resolve(ROOT, `EDUOS_CLASS_10_${s.subject.toUpperCase()}_CROSSWALK.md`), L.join("\n"));
}

// ------------------------------------------------------ outcome/atom matrix
{
  const L = head("EduOS — CBSE Class 10 Outcome and Atom Matrix (2026-27)");
  L.push("Learning-outcome integrity: every mapped topic carries ≥1 outcome; every outcome carries ≥1 atom; no orphans in either direction.", "");
  for (const s of subjects) {
    L.push(`## ${s.subject}`, "");
    L.push("| Platform unit | Official-mapped | Outcomes | Orphan outcomes | Atoms | Atoms without questions | Verdict |");
    L.push("|---|---|---|---|---|---|---|");
    for (const u of s.units) {
      const ok = u.outcomes > 0 && u.orphanOutcomes === 0 && u.atomsWithoutQuestions === 0;
      L.push(`| ${u.title} | ${u.officialMapped ? "yes" : "NO"} | ${u.outcomes} | ${u.orphanOutcomes} | ${u.atoms} | ${u.atomsWithoutQuestions} | ${ok ? "OK" : "REVIEW"} |`);
    }
    L.push("");
    const totals = s.units.reduce((a, u) => ({ o: a.o + u.outcomes, at: a.at + u.atoms }), { o: 0, at: 0 });
    L.push(`Totals — outcomes: ${totals.o}, atoms: ${totals.at}.`, "");
  }
  writeFileSync(resolve(ROOT, "EDUOS_CLASS_10_OUTCOME_ATOM_MATRIX.md"), L.join("\n"));
}

// ------------------------------------- question-depth / reassessment matrix
{
  const L = head("EduOS — CBSE Class 10 Question-Depth and Reassessment Matrix (2026-27)");
  L.push("Depth law: verified items per unit ≥ max(2 × diagnostic target, 2 × outcomes × per-outcome minimum, 2 × diagnostic minimum). The factor of two reserves a fresh reassessment set.", "");
  for (const s of subjects) {
    L.push(`## ${s.subject}`, "");
    L.push(`Diagnostic target ${s.gates.diagnosticTarget} · diagnostic minimum ${s.gates.diagnosticMinimum} · minimum per outcome ${s.gates.minQuestionsPerOutcome}.`, "");
    L.push("| Platform unit | Questions | Verified | Required | Diagnostic set | Reassessment reserve | Difficulty bands | Question types | Verdict |");
    L.push("|---|---|---|---|---|---|---|---|---|");
    for (const u of s.units) {
      const req = requiredVerifiedPerUnit(s.gates, u.outcomes);
      const diag = Math.min(u.verified, s.gates.diagnosticTarget);
      const reserve = Math.max(0, u.verified - diag);
      const ok = u.verified >= req && u.difficulties >= 2 && u.kinds >= 2;
      L.push(`| ${u.title} | ${u.questions} | ${u.verified} | ${req} | ${diag} | ${reserve} | ${u.difficulties} | ${u.kinds} | ${ok ? "OK" : "SHORTFALL"} |`);
    }
    L.push("");
  }
  L.push("Limitation: duplicate detection is not computed from the snapshot (recorded as 0) and must be re-run against the live question bank before any COMPLIANT verdict.", "");
  writeFileSync(resolve(ROOT, "EDUOS_CLASS_10_QUESTION_DEPTH_AND_REASSESSMENT_MATRIX.md"), L.join("\n"));
}

// ------------------------------------------------------------- gap register
type Gap = { id: string; subject: string; gate: string; check: string; detail: string; severity: "BLOCKING" | "MAJOR" };
const gaps: Gap[] = [];
for (const s of subjects) {
  for (const g of s.gateResults) {
    for (const c of g.checks.filter((c) => !c.pass)) {
      gaps.push({
        id: `GAP-${s.subject.slice(0, 3).toUpperCase()}-${String(gaps.length + 1).padStart(3, "0")}`,
        subject: s.subject,
        gate: g.gate,
        check: c.id,
        detail: c.detail,
        severity: g.gate === "SOURCE_GATE" || g.gate === "REVIEW_GATE" || g.gate === "CURRICULUM_GATE" ? "BLOCKING" : "MAJOR",
      });
    }
  }
}
{
  const L = head("EduOS — CBSE Class 10 Gap Register (2026-27)");
  L.push(`Total open gaps: ${gaps.length} (blocking: ${gaps.filter((g) => g.severity === "BLOCKING").length}). No remediation is authorised in this assignment; the register records state only.`, "");
  L.push("| Gap id | Subject | Gate | Check | Severity | Detail |");
  L.push("|---|---|---|---|---|---|");
  for (const g of gaps) L.push(`| ${g.id} | ${g.subject} | ${g.gate} | \`${g.check}\` | ${g.severity} | ${g.detail} |`);
  L.push("", "## Source registry issues", "");
  for (const i of sourceIssues) L.push(`- ${i.level.toUpperCase()} \`${i.code}\` — ${i.detail}`);
  if (!sourceIssues.length) L.push("- none");
  L.push("");
  writeFileSync(resolve(ROOT, "EDUOS_CLASS_10_GAP_REGISTER.md"), L.join("\n"));
}

// ------------------------------------------- machine-readable crosswalk JSON
{
  const doc = {
    generatedAt: stamp,
    validator: VALIDATOR_VERSION,
    board: snapshot.board,
    classLevel: snapshot.classLevel,
    academicSession: snapshot.academicYear,
    overallStatus: overall,
    sourceIssues,
    subjects: subjects.map((s) => ({
      subject: s.subject,
      status: s.status,
      gaps: s.gaps,
      volumeGates: s.gates,
      crosswalk: s.crosswalk,
      platformUnits: s.units,
      unmappedOfficialTopics: s.unmappedOfficialTopics,
      outOfSyllabusUnits: s.outOfSyllabusUnits,
      gateResults: s.gateResults,
    })),
    gapRegister: gaps,
  };
  writeFileSync(resolve(ROOT, "content/compliance/class-10-2026-27.crosswalk.json"), `${JSON.stringify(doc, null, 2)}\n`);
}

console.log(`bundle artefacts written — overall ${overall}, ${gaps.length} gap(s)`);
