// Generates the machine-derived sections of the Class 10 compliance audit and
// the subject crosswalks. Read-only; deterministic.
//   bun run scripts/compliance/report.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { analyse, ROOT } from "./analysis";
import { VALIDATOR_VERSION } from "../../src/lib/compliance-shared";

const { snapshot, sourceIssues, subjects, overall } = analyse();
const stamp = new Date().toISOString().slice(0, 10);
const L: string[] = [];

L.push("# EduOS — CBSE Class 10 (2026-27) Complete Coverage Audit");
L.push("");
L.push(`**Generated:** ${stamp} · **Validator:** ${VALIDATOR_VERSION} · **Source of truth:** \`content/compliance/class-10-2026-27.snapshot.json\` (live database export, read-only)`);
L.push("");
L.push(`**Overall compliance status: ${overall}**`);
L.push("");
L.push("This file is generated by `scripts/compliance/report.ts`. Do not edit by hand — re-run the exporter and the generator.");
L.push("");
L.push("## 1. Source registry state");
L.push("");
L.push(`Registry errors: ${sourceIssues.filter((i) => i.level === "error").length} · warnings: ${sourceIssues.filter((i) => i.level === "warning").length}`);
L.push("");
for (const i of sourceIssues) L.push(`- ${i.level.toUpperCase()} \`${i.code}\` — ${i.detail}`);
if (sourceIssues.length === 0) L.push("- none");
L.push("");

for (const s of subjects) {
  L.push(`## 2. ${s.subject} — ${s.status}`);
  L.push("");
  L.push(`Volume gates in force: diagnostic target ${s.gates.diagnosticTarget}, diagnostic minimum ${s.gates.diagnosticMinimum}, minimum questions per outcome ${s.gates.minQuestionsPerOutcome}. Depth law: verified items per unit ≥ max(2 × target, 2 × outcomes × per-outcome minimum, 2 × minimum).`);
  L.push("");
  L.push("### 2.1 Official unit → platform unit crosswalk");
  L.push("");
  L.push("| Official ref | Official unit | Marks | Platform unit | Outcomes | Verified | Required | Verdict |");
  L.push("|---|---|---|---|---|---|---|---|");
  for (const c of s.crosswalk) {
    const verdict = !c.mappedUnitId ? "MISSING" : c.verified >= c.required ? "OK" : "SHORTFALL";
    L.push(`| ${c.officialRef} | ${c.officialTitle} | ${c.marks} | ${c.mappedTitle ?? "—"} | ${c.outcomes} | ${c.verified} | ${c.required} | ${verdict} |`);
  }
  L.push("");
  L.push("### 2.2 Official chapter coverage");
  L.push("");
  L.push("| Official ref | Chapter | Mapped in platform |");
  L.push("|---|---|---|");
  for (const c of s.crosswalk) for (const ch of c.chapters) L.push(`| ${ch.ref} | ${ch.title} | ${ch.mapped ? "yes" : "NO"} |`);
  L.push("");
  L.push("### 2.3 Platform units present");
  L.push("");
  L.push("| Unit | Official-mapped | Outcomes | Atoms | Questions | Verified | Difficulty bands | Question types |");
  L.push("|---|---|---|---|---|---|---|---|");
  for (const u of s.units) L.push(`| ${u.title} | ${u.officialMapped ? "yes" : "NO"} | ${u.outcomes} | ${u.atoms} | ${u.questions} | ${u.verified} | ${u.difficulties} | ${u.kinds} |`);
  L.push("");
  if (s.outOfSyllabusUnits.length) {
    L.push("Active platform units with no official mapping (must be retired or mapped):");
    L.push("");
    for (const u of s.outOfSyllabusUnits) L.push(`- ${u}`);
    L.push("");
  }
  L.push("### 2.4 Gate results");
  L.push("");
  for (const g of s.gateResults) {
    L.push(`**${g.gate} — ${g.pass ? "PASS" : "FAIL"}**`);
    L.push("");
    for (const c of g.checks) L.push(`- ${c.pass ? "PASS" : "FAIL"} \`${c.id}\` — ${c.detail}`);
    L.push("");
  }
}

L.push("## 3. Known measurement limitations");
L.push("");
L.push("- Duplicate-question detection is not computed from the snapshot; it is recorded as 0 and must be re-run against the live question bank before a COMPLIANT verdict.");
L.push("- Official unit, chapter and weightage entries are unverified (`PENDING_OFFICIAL_RETRIEVAL`) — no checksummed CBSE/NCERT document was retrievable in this environment.");
L.push("- Learning-loop checks other than reassessment reserve are asserted from existing Phase 1–Wave 0 verification evidence, not re-executed here.");
L.push("");

writeFileSync(resolve(ROOT, "EDUOS_CLASS_10_2026_27_COMPLETE_COVERAGE_AUDIT.md"), L.join("\n"));
console.log(`wrote EDUOS_CLASS_10_2026_27_COMPLETE_COVERAGE_AUDIT.md — overall ${overall}`);
