// Wave 1 continuation: deterministic report + review-package generator.
//
//   bun run scripts/class9/reports.ts
//
// Read-only with respect to the database. It re-derives the packs and writes:
//   EDUOS_CLASS_9_CONTENT_VOLUME_MATRIX.md
//   EDUOS_CLASS_9_MATHEMATICS_SUBJECT_EXPERT_REVIEW_PACKAGE.md
//   EDUOS_CLASS_9_SCIENCE_SUBJECT_EXPERT_REVIEW_PACKAGE.md
//
// Every emitted question stays draft + unverified; the review packages carry
// EMPTY reviewer columns. Nothing here constitutes human review.

import { writeFileSync } from "node:fs";
import { buildReadinessMatrix, flattenOutcomes } from "../../src/lib/class9-content-schema";
import { SUBJECTS } from "./authoring";
import { buildPacks } from "./build-packs";
import { LIVE_GATES } from "./validate";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function counts<T extends string | number>(values: T[]): string {
  const m = new Map<T, number>();
  for (const v of values) m.set(v, (m.get(v) ?? 0) + 1);
  return [...m.entries()]
    .sort((a, b) => String(a[0]).localeCompare(String(b[0])))
    .map(([k, n]) => `${k}:${n}`)
    .join(" ");
}

const matrixLines: string[] = [
  "# EduOS — Class 9 Content Volume Matrix",
  "",
  "Generated by `bun run scripts/class9/reports.ts` from `content/class-9/*.json`.",
  "Requirement law: `max(2 × diagnostic_target, 2 × outcomes × min_per_outcome, 2 × diagnostic_minimum)`",
  `with live Class 10 gates (diagnostic_target ${LIVE_GATES.diagnosticTarget}, diagnostic_minimum ${LIVE_GATES.diagnosticMinimum}, min_per_outcome ${LIVE_GATES.minQuestionsPerOutcome}) → **40 verified questions per unit**.`,
  "",
  "All Class 9 content is inactive, draft and unverified: human-reviewed = 0, verified = 0, approved = 0,",
  "diagnostic-allocation ready = NO, fresh-reassessment ready = NO for every row below.",
  "",
];

for (const subject of SUBJECTS) {
  const { curriculum, questions } = buildPacks(subject);
  const qs = questions.questions;
  const rows = flattenOutcomes(curriculum);
  const matrix = buildReadinessMatrix(curriculum, qs, LIVE_GATES);

  matrixLines.push(`## ${curriculum.subjectKey} (${curriculum.catalogueCode})`, "");
  matrixLines.push(
    `Units ${curriculum.units.length} · chapters ${curriculum.units.flatMap((u) => u.chapters).length} · ` +
      `topics ${rows.length ? new Set(rows.map((r) => r.topic.id)).size : 0} · outcomes ${rows.length} · ` +
      `atoms ${rows.reduce((s, r) => s + r.outcome.atoms.length, 0)} · questions ${qs.length}`,
    "",
    "### Unit level",
    "",
    "| Unit | Title | Outcomes | Atoms | Required | Prepared | Structurally valid | Duplicate-free | Difficulty | Question types | Review-ready | Human-reviewed | Verified | Approved | Allocation ready | Reassessment ready | Shortfall | Blocking reason |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  );

  for (const u of curriculum.units) {
    const outcomes = u.chapters.flatMap((c) => c.topics.flatMap((t) => t.outcomes));
    const ids = new Set(outcomes.map((o) => o.id));
    const uq = qs.filter((q) => ids.has(q.outcomeId));
    const m = matrix.find((x) => x.unitId === u.id)!;
    matrixLines.push(
      `| ${u.id} | ${esc(u.title)} | ${outcomes.length} | ${outcomes.reduce((s, o) => s + o.atoms.length, 0)} | ${m.required} | ${uq.length} | ${uq.length} | ${uq.length} | ${counts(uq.map((q) => q.difficulty))} | ${counts(uq.map((q) => q.kind))} | ${uq.length} | 0 | 0 | 0 | NO | NO | ${m.shortfall} | ${esc(m.blockingReason)} |`,
    );
  }

  matrixLines.push("", "### Outcome and atom level", "", "| Unit | Chapter | Topic | Outcome | Atoms | Atoms covered | Questions | Difficulty | Question types |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const r of rows) {
    const oq = qs.filter((q) => q.outcomeId === r.outcome.id);
    const coveredAtoms = new Set(oq.map((q) => q.atomId)).size;
    matrixLines.push(
      `| ${r.unit.id} | ${esc(r.chapter.title)} | ${esc(r.topic.title)} | ${r.outcome.id} | ${r.outcome.atoms.length} | ${coveredAtoms} | ${oq.length} | ${counts(oq.map((q) => q.difficulty))} | ${counts(oq.map((q) => q.kind))} |`,
    );
  }
  matrixLines.push("");

  // ---- Subject-expert review package -------------------------------------
  const pkg: string[] = [
    `# EduOS — Class 9 ${curriculum.subjectKey} Subject-Expert Review Package`,
    "",
    `Board CBSE · Academic year ${curriculum.academicYear} · Class 9 · Subject ${curriculum.subjectKey} (${curriculum.catalogueCode})`,
    `Source: ${esc(curriculum.sources[0]!.title)} — ${esc(curriculum.sources[0]!.officialReference)}`,
    "",
    "## Reviewer identity (to be completed by a named human expert)",
    "",
    "| Field | Value |",
    "| --- | --- |",
    "| Reviewer name | _(empty)_ |",
    "| Reviewer expertise / qualification | _(empty)_ |",
    "| Institution | _(empty)_ |",
    "| Review start date and time (IST) | _(empty)_ |",
    "| Review completion date and time (IST) | _(empty)_ |",
    "| Final review decision (ACCEPT ALL / ACCEPT WITH CORRECTIONS / REJECT) | _(empty)_ |",
    "| Signature | _(empty)_ |",
    "",
    "## Status",
    "",
    "HUMAN_REVIEW_STATUS: READY_FOR_REVIEW — 0 HUMAN-REVIEWED.",
    "No question in this package has been reviewed, verified or approved by a human.",
    "Automated validation is not review. Reviewer decisions recorded here are the only",
    "evidence that may later move a question to `verification_state = verified`.",
    "",
    "## How to review",
    "",
    "For each question row record: Accept / Reject / Correction required, the corrected answer",
    "and corrected explanation when applicable, a curriculum-alignment note, a difficulty note,",
    "and the date-time of the decision. Leave nothing blank for items you touch.",
    "",
    "## Questions",
    "",
  ];

  for (const u of curriculum.units) {
    pkg.push(`### ${u.id} — ${u.title} (syllabus marks ${u.syllabusMarks})`, "");
    for (const c of u.chapters) {
      for (const t of c.topics) {
        for (const o of t.outcomes) {
          const oq = qs.filter((q) => q.outcomeId === o.id);
          if (!oq.length) continue;
          pkg.push(
            `#### ${o.id} — ${esc(o.title)}`,
            "",
            `Chapter ${c.ncertChapter}: ${esc(c.title)} · Topic: ${esc(t.title)} · Category ${o.category} · Bloom ${o.bloomLevel} · Diagnostic weight ${o.diagnosticWeight}`,
            "",
            `Atoms: ${o.atoms.map((a) => `${a.id} — ${esc(a.text)}`).join("; ")}`,
            "",
            "| Question ID | External ref | Atom | Type | Difficulty | Prompt | Options | Correct answer | Explanation | Provenance | Status | Verification | Accept | Reject | Correction required | Corrected answer | Corrected explanation | Alignment note | Difficulty note | Date/time |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
          );
          for (const q of oq) {
            pkg.push(
              `| ${q.id} | ${esc(q.externalRef)} | ${q.atomId} | ${q.kind} | ${q.difficulty} | ${esc(q.prompt)} | ${q.options ? esc(q.options.join(" / ")) : "—"} | ${esc(q.correctAnswer)} | ${esc(q.explanation)} | ${esc(q.provenance.sourceRef)} | ${q.status} | ${q.verificationState} | ☐ | ☐ | ☐ |  |  |  |  |  |`,
            );
          }
          pkg.push("");
        }
      }
    }
  }

  pkg.push(
    "## Reviewer summary (to be completed)",
    "",
    "| Metric | Value |",
    "| --- | --- |",
    `| Questions in package | ${qs.length} |`,
    "| Accepted | _(empty)_ |",
    "| Rejected | _(empty)_ |",
    "| Corrections required | _(empty)_ |",
    "| Human-reviewed at time of generation | 0 |",
    "",
  );

  const slug = curriculum.subjectKey.toUpperCase();
  writeFileSync(`EDUOS_CLASS_9_${slug}_SUBJECT_EXPERT_REVIEW_PACKAGE.md`, pkg.join("\n"));
  console.log(`wrote EDUOS_CLASS_9_${slug}_SUBJECT_EXPERT_REVIEW_PACKAGE.md (${qs.length} questions)`);
}

writeFileSync("EDUOS_CLASS_9_CONTENT_VOLUME_MATRIX.md", matrixLines.join("\n") + "\n");
console.log("wrote EDUOS_CLASS_9_CONTENT_VOLUME_MATRIX.md");
