import type { UnitExtension } from "../extension-types";
import type { AuthoredQuestion } from "../authoring";

export const EXT: UnitExtension = {
  unitId: "C9-MAT-U5",
  newTopics: [
    {
      chapter: 2,
      topic: {
        title: "Surface area and volume of cuboids and cubes",
        outcomes: [
          {
            title: "Calculate surface area and volume of cuboids and cubes and solve related problems",
            category: "procedural",
            bloom: "apply",
            difficulty: 2,
            weight: 4,
            types: ["mcq", "short_answer", "true_false", "applied_mcq"],
            atoms: [
              "Apply total surface area of a cuboid = 2(lb + bh + hl) and of a cube = 6a²",
              "Apply volume of a cuboid = l × b × h and of a cube = a³",
            ],
            prerequisites: [],
            questions: [
              {
                kind: "short_answer",
                difficulty: 2,
                prompt: "Find the total surface area of a cuboid of length 8 cm, breadth 5 cm and height 3 cm.",
                answer: "158 cm²",
                explanation: "TSA = 2(lb + bh + hl) = 2(40 + 15 + 24) = 2 × 79 = 158 cm².",
              },
              {
                kind: "mcq",
                difficulty: 2,
                prompt: "What is the volume of a cube whose edge measures 6 cm?",
                options: ["36 cm³", "108 cm³", "216 cm³", "196 cm³"],
                answer: "216 cm³",
                explanation: "Volume of a cube = a³ = 6³ = 216 cm³.",
              },
              {
                kind: "applied_mcq",
                difficulty: 3,
                prompt: "A closed rectangular tank measures 10 m by 6 m by 4 m. How much sheet metal is needed to make it?",
                options: ["208 m²", "240 m²", "104 m²", "416 m²"],
                answer: "208 m²",
                explanation: "TSA = 2(lb + bh + hl) = 2(60 + 24 + 40) = 2 × 104 = 208 m².",
              },
              {
                kind: "true_false",
                difficulty: 1,
                prompt: "The volume of a cube with edge 4 cm is 64 cm³.",
                options: ["True", "False"],
                answer: "True",
                explanation: "Volume of a cube = a³ = 4³ = 64 cm³, so the statement is true.",
              },
              {
                kind: "short_answer",
                difficulty: 3,
                prompt: "A cuboidal box has volume 240 cm³, length 8 cm and breadth 5 cm. Find its height.",
                answer: "6 cm",
                explanation: "Volume = l × b × h, so h = 240/(8 × 5) = 240/40 = 6 cm.",
              },
              {
                kind: "mcq",
                difficulty: 4,
                prompt: "If the edge of a cube is doubled, its total surface area becomes:",
                options: ["twice as large", "three times as large", "four times as large", "eight times as large"],
                answer: "four times as large",
                explanation: "TSA = 6a² depends on the square of the edge, so doubling a multiplies TSA by 2² = 4.",
              },
            ],
          },
        ],
      },
    },
    {
      chapter: 2,
      topic: {
        title: "Surface area and volume of hemispheres",
        outcomes: [
          {
            title: "Calculate curved and total surface area and volume of a hemisphere",
            category: "procedural",
            bloom: "apply",
            difficulty: 3,
            weight: 4,
            types: ["mcq", "short_answer", "assertion_reason", "true_false"],
            atoms: [
              "Apply CSA of a hemisphere = 2πr² and TSA = 3πr²",
              "Apply volume of a hemisphere = (2/3)πr³",
            ],
            prerequisites: [],
            questions: [
              {
                kind: "short_answer",
                difficulty: 3,
                prompt: "Find the curved surface area of a hemisphere of radius 7 cm. Take π = 22/7.",
                answer: "308 cm²",
                explanation: "CSA = 2πr² = 2 × (22/7) × 7 × 7 = 308 cm².",
              },
              {
                kind: "mcq",
                difficulty: 3,
                prompt: "What is the total surface area of a solid hemisphere of radius 7 cm? Take π = 22/7.",
                options: ["308 cm²", "462 cm²", "154 cm²", "616 cm²"],
                answer: "462 cm²",
                explanation: "TSA = 3πr² = 3 × (22/7) × 7 × 7 = 462 cm².",
              },
              {
                kind: "short_answer",
                difficulty: 3,
                prompt: "Find the volume of a hemisphere of radius 3 cm. Take π = 3.14.",
                answer: "56.52 cm³",
                explanation: "Volume = (2/3)πr³ = (2/3) × 3.14 × 27 = 56.52 cm³.",
              },
              {
                kind: "true_false",
                difficulty: 2,
                prompt: "The curved surface area of a hemisphere is exactly half the surface area of a sphere of the same radius.",
                options: ["True", "False"],
                answer: "True",
                explanation: "Sphere surface area = 4πr² while hemisphere CSA = 2πr², which is exactly half.",
              },
              {
                kind: "assertion_reason",
                difficulty: 4,
                prompt: "Assertion: The total surface area of a solid hemisphere of radius r is 3πr². Reason: A solid hemisphere consists of the curved surface 2πr² plus the flat circular base πr².",
                options: [
                  "Both assertion and reason are true and reason correctly explains the assertion",
                  "Both assertion and reason are true but reason does not explain the assertion",
                  "Assertion is true but reason is false",
                  "Assertion is false but reason is true",
                ],
                answer: "Both assertion and reason are true and reason correctly explains the assertion",
                explanation: "TSA = CSA + base area = 2πr² + πr² = 3πr², so the reason correctly justifies the assertion.",
              },
              {
                kind: "mcq",
                difficulty: 2,
                prompt: "A bowl is shaped like a hemisphere of radius 5 cm. What is its volume? Take π = 22/7.",
                options: ["261.9 cm³", "523.8 cm³", "392.9 cm³", "130.9 cm³"],
                answer: "261.9 cm³",
                explanation: "Volume = (2/3)πr³ = (2/3) × (22/7) × 125 ≈ 261.9 cm³.",
              },
            ],
          },
        ],
      },
    },
    {
      chapter: 2,
      topic: {
        title: "Applied capacity and cost problems on solids",
        outcomes: [
          {
            title: "Solve real-life problems involving capacity, material cost and painting of solids",
            category: "application",
            bloom: "apply",
            difficulty: 4,
            weight: 5,
            types: ["applied_mcq", "short_answer", "mcq", "true_false"],
            atoms: [
              "Convert volume to capacity in litres and compute cost using a given rate",
              "Combine surface area formulae to compute the cost of painting or covering composite solids",
            ],
            prerequisites: [],
            questions: [
              {
                kind: "applied_mcq",
                difficulty: 3,
                prompt: "A cylindrical water tank has radius 7 m and height 10 m. How many litres of water can it hold? Take π = 22/7 and 1 m³ = 1000 litres.",
                options: ["1540000 litres", "770000 litres", "220000 litres", "1078000 litres"],
                answer: "1540000 litres",
                explanation: "Volume = πr²h = (22/7) × 49 × 10 = 1540 m³ = 1540 × 1000 = 1540000 litres.",
              },
              {
                kind: "short_answer",
                difficulty: 4,
                prompt: "The curved surface of a cylindrical pillar of radius 1.4 m and height 5 m is to be painted at Rs 20 per m². Find the cost. Take π = 22/7.",
                answer: "Rs 880",
                explanation: "CSA = 2πrh = 2 × (22/7) × 1.4 × 5 = 44 m². Cost = 44 × 20 = Rs 880.",
              },
              {
                kind: "applied_mcq",
                difficulty: 4,
                prompt: "A conical tent has radius 7 m and slant height 25 m. Find the cost of the canvas at Rs 15 per m². Take π = 22/7.",
                options: ["Rs 8250", "Rs 4125", "Rs 16500", "Rs 5500"],
                answer: "Rs 8250",
                explanation: "CSA = πrl = (22/7) × 7 × 25 = 550 m². Cost = 550 × 15 = Rs 8250.",
              },
              {
                kind: "mcq",
                difficulty: 3,
                prompt: "A cube-shaped tank of edge 2 m is filled with water. How many litres does it hold? (1 m³ = 1000 litres)",
                options: ["8000 litres", "4000 litres", "2000 litres", "6000 litres"],
                answer: "8000 litres",
                explanation: "Volume = a³ = 2³ = 8 m³ = 8 × 1000 = 8000 litres.",
              },
              {
                kind: "true_false",
                difficulty: 2,
                prompt: "Painting only the curved surface of a closed cylindrical drum ignores its two circular ends.",
                options: ["True", "False"],
                answer: "True",
                explanation: "Curved surface area 2πrh excludes the two circular ends of area πr² each, so the statement is true.",
              },
              {
                kind: "short_answer",
                difficulty: 5,
                prompt: "A hemispherical bowl of radius 10.5 cm is to be coated with silver on the inside at Rs 4 per cm². Find the cost. Take π = 22/7.",
                answer: "Rs 2772",
                explanation: "Inner CSA = 2πr² = 2 × (22/7) × 10.5 × 10.5 = 693 cm². Cost = 693 × 4 = Rs 2772.",
              },
              {
                kind: "applied_mcq",
                difficulty: 4,
                prompt: "Milk is stored in a cylindrical can of radius 14 cm and height 30 cm. How many litres of milk can it hold? Take π = 22/7 and 1000 cm³ = 1 litre.",
                options: ["18.48 litres", "9.24 litres", "36.96 litres", "13.86 litres"],
                answer: "18.48 litres",
                explanation: "Volume = πr²h = (22/7) × 196 × 30 = 18480 cm³ = 18.48 litres.",
              },
            ],
          },
        ],
      },
    },
  ],
  extraQuestions: {
    "C9-MAT-U5-CH1-T1-O1": [
      {
        kind: "mcq",
        difficulty: 2,
        prompt: "Find the semi-perimeter of a triangle with sides 6 cm, 8 cm and 10 cm.",
        options: ["12 cm", "24 cm", "14 cm", "9 cm"],
        answer: "12 cm",
        explanation: "s = (6 + 8 + 10)/2 = 24/2 = 12 cm.",
      },
      {
        kind: "short_answer",
        difficulty: 3,
        prompt: "Find the area of a triangle with sides 13 cm, 14 cm and 15 cm using Heron's formula.",
        answer: "84 cm²",
        explanation: "s = (13+14+15)/2 = 21. Area = √(21 × 8 × 7 × 6) = √7056 = 84 cm².",
      },
      {
        kind: "true_false",
        difficulty: 2,
        prompt: "Heron's formula can be used to find the area of a triangle even when its height is not known.",
        options: ["True", "False"],
        answer: "True",
        explanation: "Heron's formula uses only the three side lengths, so no height is required, making the statement true.",
      },
      {
        kind: "applied_mcq",
        difficulty: 4,
        prompt: "The sides of a triangular signboard are 18 m, 24 m and 30 m. Find its area.",
        options: ["216 m²", "270 m²", "360 m²", "180 m²"],
        answer: "216 m²",
        explanation: "s = (18+24+30)/2 = 36. Area = √(36 × 18 × 12 × 6) = √46656 = 216 m².",
      },
      {
        kind: "assertion_reason",
        difficulty: 4,
        prompt: "Assertion: A triangle with sides 5 cm, 5 cm and 8 cm has area 12 cm². Reason: An isosceles triangle's area equals half the product of its two equal sides.",
        options: [
          "Both assertion and reason are true and reason correctly explains the assertion",
          "Both assertion and reason are true but reason does not explain the assertion",
          "Assertion is true but reason is false",
          "Assertion is false but reason is true",
        ],
        answer: "Assertion is true but reason is false",
        explanation: "s = (5+5+8)/2 = 9, Area = √(9×4×4×1) = √144 = 12 cm², so the assertion is true, but the reason's formula is not a general rule for isosceles triangles.",
      },
    ],
    "C9-MAT-U5-CH2-T1-O1": [
      {
        kind: "short_answer",
        difficulty: 3,
        prompt: "Find the total surface area of a cylinder of radius 7 cm and height 10 cm. Take π = 22/7.",
        answer: "748 cm²",
        explanation: "TSA = 2πr(h + r) = 2 × (22/7) × 7 × 17 = 748 cm².",
      },
      {
        kind: "mcq",
        difficulty: 3,
        prompt: "Find the curved surface area of a cone with radius 3.5 cm and slant height 10 cm. Take π = 22/7.",
        options: ["110 cm²", "220 cm²", "77 cm²", "55 cm²"],
        answer: "110 cm²",
        explanation: "CSA = πrl = (22/7) × 3.5 × 10 = 110 cm².",
      },
      {
        kind: "true_false",
        difficulty: 2,
        prompt: "The surface area of a sphere of radius 7 cm is 616 cm² when π = 22/7.",
        options: ["True", "False"],
        answer: "True",
        explanation: "Surface area = 4πr² = 4 × (22/7) × 49 = 616 cm², so the statement is true.",
      },
      {
        kind: "applied_mcq",
        difficulty: 4,
        prompt: "A cone has base radius 5 cm and height 12 cm. Find its curved surface area. Take π = 3.14.",
        options: ["204.1 cm²", "188.4 cm²", "94.2 cm²", "157 cm²"],
        answer: "204.1 cm²",
        explanation: "Slant height l = √(5² + 12²) = 13 cm. CSA = πrl = 3.14 × 5 × 13 = 204.1 cm².",
      },
      {
        kind: "short_answer",
        difficulty: 4,
        prompt: "The diameter of a sphere is 21 cm. Find its total surface area. Take π = 22/7.",
        answer: "1386 cm²",
        explanation: "r = 10.5 cm. Surface area = 4πr² = 4 × (22/7) × 10.5 × 10.5 = 1386 cm².",
      },
    ],
    "C9-MAT-U5-CH2-T2-O1": [
      {
        kind: "short_answer",
        difficulty: 3,
        prompt: "Find the volume of a cylinder of radius 7 cm and height 15 cm. Take π = 22/7.",
        answer: "2310 cm³",
        explanation: "Volume = πr²h = (22/7) × 49 × 15 = 2310 cm³.",
      },
      {
        kind: "mcq",
        difficulty: 3,
        prompt: "Find the volume of a cone with radius 6 cm and height 7 cm. Take π = 22/7.",
        options: ["264 cm³", "792 cm³", "132 cm³", "396 cm³"],
        answer: "264 cm³",
        explanation: "Volume = (1/3)πr²h = (1/3) × (22/7) × 36 × 7 = 264 cm³.",
      },
      {
        kind: "true_false",
        difficulty: 2,
        prompt: "The volume of a sphere of radius 3 cm is 36π cm³.",
        options: ["True", "False"],
        answer: "True",
        explanation: "Volume = (4/3)πr³ = (4/3)π(27) = 36π cm³, so the statement is true.",
      },
      {
        kind: "applied_mcq",
        difficulty: 4,
        prompt: "A cylindrical bucket of radius 14 cm and height 20 cm is completely filled with sand. Find the volume of sand. Take π = 22/7.",
        options: ["12320 cm³", "6160 cm³", "24640 cm³", "8800 cm³"],
        answer: "12320 cm³",
        explanation: "Volume = πr²h = (22/7) × 196 × 20 = 12320 cm³.",
      },
      {
        kind: "short_answer",
        difficulty: 5,
        prompt: "A metal sphere of radius 4.2 cm is melted and recast into a cone of the same radius. Find the height of the cone.",
        answer: "16.8 cm",
        explanation: "Equal volumes: (4/3)πr³ = (1/3)πr²h, so h = 4r = 4 × 4.2 = 16.8 cm.",
      },
    ],
  } satisfies Record<string, AuthoredQuestion[]>,
};
