/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssessmentAuditRouteImport } from './routes/_authenticated/assessment-audit'
import { Route as AuthenticatedAssessmentBlueprintRouteImport } from './routes/_authenticated/assessment-blueprint'
import { Route as AuthenticatedAssessmentBlueprintAuditRouteImport } from './routes/_authenticated/assessment-blueprint-audit'
import { Route as AuthenticatedAssessmentBuilderRouteImport } from './routes/_authenticated/assessment-builder'
import { Route as AuthenticatedAssessmentBuilderAuditRouteImport } from './routes/_authenticated/assessment-builder-audit'
import { Route as AuthenticatedAssessmentProofRouteImport } from './routes/_authenticated/assessment-proof'
import { Route as AuthenticatedAssessmentVerificationRouteImport } from './routes/_authenticated/assessment-verification'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedCurriculumAuditRouteImport } from './routes/_authenticated/curriculum-audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticEngineRouteImport } from './routes/_authenticated/diagnostic-engine'
import { Route as AuthenticatedDiagnosticEngineAuditRouteImport } from './routes/_authenticated/diagnostic-engine-audit'
import { Route as AuthenticatedGapAnalysisRouteImport } from './routes/_authenticated/gap-analysis'
import { Route as AuthenticatedGapAnalysisAuditRouteImport } from './routes/_authenticated/gap-analysis-audit'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInterventionsRouteImport } from './routes/_authenticated/interventions'
import { Route as AuthenticatedLaunchAuditRouteImport } from './routes/_authenticated/launch-audit'
import { Route as AuthenticatedLearnersRouteImport } from './routes/_authenticated/learners'
import { Route as AuthenticatedOutcomeProofRouteImport } from './routes/_authenticated/outcome-proof'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedPilotEvidenceRouteImport } from './routes/_authenticated/pilot-evidence'
import { Route as AuthenticatedQuestionBankRouteImport } from './routes/_authenticated/question-bank'
import { Route as AuthenticatedQuestionBankAuditRouteImport } from './routes/_authenticated/question-bank-audit'
import { Route as AuthenticatedQuickStartRouteImport } from './routes/_authenticated/quick-start'
import { Route as AuthenticatedRlsVerificationRouteImport } from './routes/_authenticated/rls-verification'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSprint3AuditRouteImport } from './routes/_authenticated/sprint-3-audit'
import { Route as AuthenticatedSprint4AuditRouteImport } from './routes/_authenticated/sprint-4-audit'
import { Route as AuthenticatedSprint5AuditRouteImport } from './routes/_authenticated/sprint-5-audit'
import { Route as AuthenticatedUxPhase1PlanRouteImport } from './routes/_authenticated/ux-phase1-plan'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as DiagnosticIndexRouteImport } from './routes/diagnostic.index'
import { Route as AuthenticatedAssessmentAssessmentIdRouteImport } from './routes/_authenticated/assessment.$assessmentId'
import { Route as AuthenticatedLearnersLearnerIdRouteImport } from './routes/_authenticated/learners.$learnerId'
import { Route as AuthenticatedSessionSessionIdRouteImport } from './routes/_authenticated/session.$sessionId'
import { Route as AuthenticatedTutorSessionIdRouteImport } from './routes/_authenticated/tutor.$sessionId'
import { Route as DiagnosticCheckoutOrderRefRouteImport } from './routes/diagnostic.checkout.$orderRef'
import { Route as DiagnosticReportTokenRouteImport } from './routes/diagnostic.report.$token'
import { Route as DiagnosticSessionTokenRouteImport } from './routes/diagnostic.session.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentAuditRoute =
  AuthenticatedAssessmentAuditRouteImport.update({
    id: '/assessment-audit',
    path: '/assessment-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentBlueprintRoute =
  AuthenticatedAssessmentBlueprintRouteImport.update({
    id: '/assessment-blueprint',
    path: '/assessment-blueprint',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentBlueprintAuditRoute =
  AuthenticatedAssessmentBlueprintAuditRouteImport.update({
    id: '/assessment-blueprint-audit',
    path: '/assessment-blueprint-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentBuilderRoute =
  AuthenticatedAssessmentBuilderRouteImport.update({
    id: '/assessment-builder',
    path: '/assessment-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentBuilderAuditRoute =
  AuthenticatedAssessmentBuilderAuditRouteImport.update({
    id: '/assessment-builder-audit',
    path: '/assessment-builder-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentProofRoute =
  AuthenticatedAssessmentProofRouteImport.update({
    id: '/assessment-proof',
    path: '/assessment-proof',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentVerificationRoute =
  AuthenticatedAssessmentVerificationRouteImport.update({
    id: '/assessment-verification',
    path: '/assessment-verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumAuditRoute =
  AuthenticatedCurriculumAuditRouteImport.update({
    id: '/curriculum-audit',
    path: '/curriculum-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticEngineRoute =
  AuthenticatedDiagnosticEngineRouteImport.update({
    id: '/diagnostic-engine',
    path: '/diagnostic-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticEngineAuditRoute =
  AuthenticatedDiagnosticEngineAuditRouteImport.update({
    id: '/diagnostic-engine-audit',
    path: '/diagnostic-engine-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGapAnalysisRoute =
  AuthenticatedGapAnalysisRouteImport.update({
    id: '/gap-analysis',
    path: '/gap-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGapAnalysisAuditRoute =
  AuthenticatedGapAnalysisAuditRouteImport.update({
    id: '/gap-analysis-audit',
    path: '/gap-analysis-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterventionsRoute =
  AuthenticatedInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaunchAuditRoute =
  AuthenticatedLaunchAuditRouteImport.update({
    id: '/launch-audit',
    path: '/launch-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnersRoute = AuthenticatedLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutcomeProofRoute =
  AuthenticatedOutcomeProofRouteImport.update({
    id: '/outcome-proof',
    path: '/outcome-proof',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotEvidenceRoute =
  AuthenticatedPilotEvidenceRouteImport.update({
    id: '/pilot-evidence',
    path: '/pilot-evidence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankRoute =
  AuthenticatedQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankAuditRoute =
  AuthenticatedQuestionBankAuditRouteImport.update({
    id: '/question-bank-audit',
    path: '/question-bank-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuickStartRoute = AuthenticatedQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRlsVerificationRoute =
  AuthenticatedRlsVerificationRouteImport.update({
    id: '/rls-verification',
    path: '/rls-verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSprint3AuditRoute =
  AuthenticatedSprint3AuditRouteImport.update({
    id: '/sprint-3-audit',
    path: '/sprint-3-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprint4AuditRoute =
  AuthenticatedSprint4AuditRouteImport.update({
    id: '/sprint-4-audit',
    path: '/sprint-4-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprint5AuditRoute =
  AuthenticatedSprint5AuditRouteImport.update({
    id: '/sprint-5-audit',
    path: '/sprint-5-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUxPhase1PlanRoute =
  AuthenticatedUxPhase1PlanRouteImport.update({
    id: '/ux-phase1-plan',
    path: '/ux-phase1-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DiagnosticIndexRoute = DiagnosticIndexRouteImport.update({
  id: '/diagnostic/',
  path: '/diagnostic/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessmentAssessmentIdRoute =
  AuthenticatedAssessmentAssessmentIdRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnersLearnerIdRoute =
  AuthenticatedLearnersLearnerIdRouteImport.update({
    id: '/$learnerId',
    path: '/$learnerId',
    getParentRoute: () => AuthenticatedLearnersRoute,
  } as any)
const AuthenticatedSessionSessionIdRoute =
  AuthenticatedSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutorSessionIdRoute =
  AuthenticatedTutorSessionIdRouteImport.update({
    id: '/tutor/$sessionId',
    path: '/tutor/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DiagnosticCheckoutOrderRefRoute =
  DiagnosticCheckoutOrderRefRouteImport.update({
    id: '/diagnostic/checkout/$orderRef',
    path: '/diagnostic/checkout/$orderRef',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticReportTokenRoute = DiagnosticReportTokenRouteImport.update({
  id: '/diagnostic/report/$token',
  path: '/diagnostic/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticSessionTokenRoute = DiagnosticSessionTokenRouteImport.update({
  id: '/diagnostic/session/$token',
  path: '/diagnostic/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/assessment-blueprint': typeof AuthenticatedAssessmentBlueprintRoute
  '/assessment-blueprint-audit': typeof AuthenticatedAssessmentBlueprintAuditRoute
  '/assessment-builder': typeof AuthenticatedAssessmentBuilderRoute
  '/assessment-builder-audit': typeof AuthenticatedAssessmentBuilderAuditRoute
  '/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/curriculum-audit': typeof AuthenticatedCurriculumAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic-engine': typeof AuthenticatedDiagnosticEngineRoute
  '/diagnostic-engine-audit': typeof AuthenticatedDiagnosticEngineAuditRoute
  '/gap-analysis': typeof AuthenticatedGapAnalysisRoute
  '/gap-analysis-audit': typeof AuthenticatedGapAnalysisAuditRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/outcome-proof': typeof AuthenticatedOutcomeProofRoute
  '/parent': typeof AuthenticatedParentRoute
  '/pilot-evidence': typeof AuthenticatedPilotEvidenceRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/question-bank-audit': typeof AuthenticatedQuestionBankAuditRoute
  '/quick-start': typeof AuthenticatedQuickStartRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/ux-phase1-plan': typeof AuthenticatedUxPhase1PlanRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
  '/diagnostic/checkout/$orderRef': typeof DiagnosticCheckoutOrderRefRoute
  '/diagnostic/report/$token': typeof DiagnosticReportTokenRoute
  '/diagnostic/session/$token': typeof DiagnosticSessionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/assessment-blueprint': typeof AuthenticatedAssessmentBlueprintRoute
  '/assessment-blueprint-audit': typeof AuthenticatedAssessmentBlueprintAuditRoute
  '/assessment-builder': typeof AuthenticatedAssessmentBuilderRoute
  '/assessment-builder-audit': typeof AuthenticatedAssessmentBuilderAuditRoute
  '/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/curriculum-audit': typeof AuthenticatedCurriculumAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic-engine': typeof AuthenticatedDiagnosticEngineRoute
  '/diagnostic-engine-audit': typeof AuthenticatedDiagnosticEngineAuditRoute
  '/gap-analysis': typeof AuthenticatedGapAnalysisRoute
  '/gap-analysis-audit': typeof AuthenticatedGapAnalysisAuditRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/outcome-proof': typeof AuthenticatedOutcomeProofRoute
  '/parent': typeof AuthenticatedParentRoute
  '/pilot-evidence': typeof AuthenticatedPilotEvidenceRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/question-bank-audit': typeof AuthenticatedQuestionBankAuditRoute
  '/quick-start': typeof AuthenticatedQuickStartRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/ux-phase1-plan': typeof AuthenticatedUxPhase1PlanRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/diagnostic': typeof DiagnosticIndexRoute
  '/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
  '/diagnostic/checkout/$orderRef': typeof DiagnosticCheckoutOrderRefRoute
  '/diagnostic/report/$token': typeof DiagnosticReportTokenRoute
  '/diagnostic/session/$token': typeof DiagnosticSessionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/_authenticated/assessment-blueprint': typeof AuthenticatedAssessmentBlueprintRoute
  '/_authenticated/assessment-blueprint-audit': typeof AuthenticatedAssessmentBlueprintAuditRoute
  '/_authenticated/assessment-builder': typeof AuthenticatedAssessmentBuilderRoute
  '/_authenticated/assessment-builder-audit': typeof AuthenticatedAssessmentBuilderAuditRoute
  '/_authenticated/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/_authenticated/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/curriculum-audit': typeof AuthenticatedCurriculumAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostic-engine': typeof AuthenticatedDiagnosticEngineRoute
  '/_authenticated/diagnostic-engine-audit': typeof AuthenticatedDiagnosticEngineAuditRoute
  '/_authenticated/gap-analysis': typeof AuthenticatedGapAnalysisRoute
  '/_authenticated/gap-analysis-audit': typeof AuthenticatedGapAnalysisAuditRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/interventions': typeof AuthenticatedInterventionsRoute
  '/_authenticated/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/_authenticated/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/_authenticated/outcome-proof': typeof AuthenticatedOutcomeProofRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/pilot-evidence': typeof AuthenticatedPilotEvidenceRoute
  '/_authenticated/question-bank': typeof AuthenticatedQuestionBankRoute
  '/_authenticated/question-bank-audit': typeof AuthenticatedQuestionBankAuditRoute
  '/_authenticated/quick-start': typeof AuthenticatedQuickStartRoute
  '/_authenticated/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/_authenticated/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/_authenticated/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/_authenticated/ux-phase1-plan': typeof AuthenticatedUxPhase1PlanRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/_authenticated/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/_authenticated/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/_authenticated/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/_authenticated/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
  '/diagnostic/checkout/$orderRef': typeof DiagnosticCheckoutOrderRefRoute
  '/diagnostic/report/$token': typeof DiagnosticReportTokenRoute
  '/diagnostic/session/$token': typeof DiagnosticSessionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/assessment-audit'
    | '/assessment-blueprint'
    | '/assessment-blueprint-audit'
    | '/assessment-builder'
    | '/assessment-builder-audit'
    | '/assessment-proof'
    | '/assessment-verification'
    | '/assessments'
    | '/assignments'
    | '/curriculum'
    | '/curriculum-audit'
    | '/dashboard'
    | '/diagnostic-engine'
    | '/diagnostic-engine-audit'
    | '/gap-analysis'
    | '/gap-analysis-audit'
    | '/help'
    | '/home'
    | '/interventions'
    | '/launch-audit'
    | '/learners'
    | '/outcome-proof'
    | '/parent'
    | '/pilot-evidence'
    | '/question-bank'
    | '/question-bank-audit'
    | '/quick-start'
    | '/rls-verification'
    | '/settings'
    | '/sprint-3-audit'
    | '/sprint-4-audit'
    | '/sprint-5-audit'
    | '/ux-phase1-plan'
    | '/verification'
    | '/diagnostic/'
    | '/assessment/$assessmentId'
    | '/learners/$learnerId'
    | '/session/$sessionId'
    | '/tutor/$sessionId'
    | '/diagnostic/checkout/$orderRef'
    | '/diagnostic/report/$token'
    | '/diagnostic/session/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/assessment-audit'
    | '/assessment-blueprint'
    | '/assessment-blueprint-audit'
    | '/assessment-builder'
    | '/assessment-builder-audit'
    | '/assessment-proof'
    | '/assessment-verification'
    | '/assessments'
    | '/assignments'
    | '/curriculum'
    | '/curriculum-audit'
    | '/dashboard'
    | '/diagnostic-engine'
    | '/diagnostic-engine-audit'
    | '/gap-analysis'
    | '/gap-analysis-audit'
    | '/help'
    | '/home'
    | '/interventions'
    | '/launch-audit'
    | '/learners'
    | '/outcome-proof'
    | '/parent'
    | '/pilot-evidence'
    | '/question-bank'
    | '/question-bank-audit'
    | '/quick-start'
    | '/rls-verification'
    | '/settings'
    | '/sprint-3-audit'
    | '/sprint-4-audit'
    | '/sprint-5-audit'
    | '/ux-phase1-plan'
    | '/verification'
    | '/diagnostic'
    | '/assessment/$assessmentId'
    | '/learners/$learnerId'
    | '/session/$sessionId'
    | '/tutor/$sessionId'
    | '/diagnostic/checkout/$orderRef'
    | '/diagnostic/report/$token'
    | '/diagnostic/session/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/assessment-audit'
    | '/_authenticated/assessment-blueprint'
    | '/_authenticated/assessment-blueprint-audit'
    | '/_authenticated/assessment-builder'
    | '/_authenticated/assessment-builder-audit'
    | '/_authenticated/assessment-proof'
    | '/_authenticated/assessment-verification'
    | '/_authenticated/assessments'
    | '/_authenticated/assignments'
    | '/_authenticated/curriculum'
    | '/_authenticated/curriculum-audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostic-engine'
    | '/_authenticated/diagnostic-engine-audit'
    | '/_authenticated/gap-analysis'
    | '/_authenticated/gap-analysis-audit'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/interventions'
    | '/_authenticated/launch-audit'
    | '/_authenticated/learners'
    | '/_authenticated/outcome-proof'
    | '/_authenticated/parent'
    | '/_authenticated/pilot-evidence'
    | '/_authenticated/question-bank'
    | '/_authenticated/question-bank-audit'
    | '/_authenticated/quick-start'
    | '/_authenticated/rls-verification'
    | '/_authenticated/settings'
    | '/_authenticated/sprint-3-audit'
    | '/_authenticated/sprint-4-audit'
    | '/_authenticated/sprint-5-audit'
    | '/_authenticated/ux-phase1-plan'
    | '/_authenticated/verification'
    | '/diagnostic/'
    | '/_authenticated/assessment/$assessmentId'
    | '/_authenticated/learners/$learnerId'
    | '/_authenticated/session/$sessionId'
    | '/_authenticated/tutor/$sessionId'
    | '/diagnostic/checkout/$orderRef'
    | '/diagnostic/report/$token'
    | '/diagnostic/session/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DiagnosticIndexRoute: typeof DiagnosticIndexRoute
  DiagnosticCheckoutOrderRefRoute: typeof DiagnosticCheckoutOrderRefRoute
  DiagnosticReportTokenRoute: typeof DiagnosticReportTokenRoute
  DiagnosticSessionTokenRoute: typeof DiagnosticSessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-audit': {
      id: '/_authenticated/assessment-audit'
      path: '/assessment-audit'
      fullPath: '/assessment-audit'
      preLoaderRoute: typeof AuthenticatedAssessmentAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-blueprint': {
      id: '/_authenticated/assessment-blueprint'
      path: '/assessment-blueprint'
      fullPath: '/assessment-blueprint'
      preLoaderRoute: typeof AuthenticatedAssessmentBlueprintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-blueprint-audit': {
      id: '/_authenticated/assessment-blueprint-audit'
      path: '/assessment-blueprint-audit'
      fullPath: '/assessment-blueprint-audit'
      preLoaderRoute: typeof AuthenticatedAssessmentBlueprintAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-builder': {
      id: '/_authenticated/assessment-builder'
      path: '/assessment-builder'
      fullPath: '/assessment-builder'
      preLoaderRoute: typeof AuthenticatedAssessmentBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-builder-audit': {
      id: '/_authenticated/assessment-builder-audit'
      path: '/assessment-builder-audit'
      fullPath: '/assessment-builder-audit'
      preLoaderRoute: typeof AuthenticatedAssessmentBuilderAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-proof': {
      id: '/_authenticated/assessment-proof'
      path: '/assessment-proof'
      fullPath: '/assessment-proof'
      preLoaderRoute: typeof AuthenticatedAssessmentProofRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-verification': {
      id: '/_authenticated/assessment-verification'
      path: '/assessment-verification'
      fullPath: '/assessment-verification'
      preLoaderRoute: typeof AuthenticatedAssessmentVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum-audit': {
      id: '/_authenticated/curriculum-audit'
      path: '/curriculum-audit'
      fullPath: '/curriculum-audit'
      preLoaderRoute: typeof AuthenticatedCurriculumAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic-engine': {
      id: '/_authenticated/diagnostic-engine'
      path: '/diagnostic-engine'
      fullPath: '/diagnostic-engine'
      preLoaderRoute: typeof AuthenticatedDiagnosticEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic-engine-audit': {
      id: '/_authenticated/diagnostic-engine-audit'
      path: '/diagnostic-engine-audit'
      fullPath: '/diagnostic-engine-audit'
      preLoaderRoute: typeof AuthenticatedDiagnosticEngineAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gap-analysis': {
      id: '/_authenticated/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof AuthenticatedGapAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gap-analysis-audit': {
      id: '/_authenticated/gap-analysis-audit'
      path: '/gap-analysis-audit'
      fullPath: '/gap-analysis-audit'
      preLoaderRoute: typeof AuthenticatedGapAnalysisAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interventions': {
      id: '/_authenticated/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthenticatedInterventionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launch-audit': {
      id: '/_authenticated/launch-audit'
      path: '/launch-audit'
      fullPath: '/launch-audit'
      preLoaderRoute: typeof AuthenticatedLaunchAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners': {
      id: '/_authenticated/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof AuthenticatedLearnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outcome-proof': {
      id: '/_authenticated/outcome-proof'
      path: '/outcome-proof'
      fullPath: '/outcome-proof'
      preLoaderRoute: typeof AuthenticatedOutcomeProofRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilot-evidence': {
      id: '/_authenticated/pilot-evidence'
      path: '/pilot-evidence'
      fullPath: '/pilot-evidence'
      preLoaderRoute: typeof AuthenticatedPilotEvidenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank': {
      id: '/_authenticated/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AuthenticatedQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank-audit': {
      id: '/_authenticated/question-bank-audit'
      path: '/question-bank-audit'
      fullPath: '/question-bank-audit'
      preLoaderRoute: typeof AuthenticatedQuestionBankAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-start': {
      id: '/_authenticated/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof AuthenticatedQuickStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rls-verification': {
      id: '/_authenticated/rls-verification'
      path: '/rls-verification'
      fullPath: '/rls-verification'
      preLoaderRoute: typeof AuthenticatedRlsVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-3-audit': {
      id: '/_authenticated/sprint-3-audit'
      path: '/sprint-3-audit'
      fullPath: '/sprint-3-audit'
      preLoaderRoute: typeof AuthenticatedSprint3AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-4-audit': {
      id: '/_authenticated/sprint-4-audit'
      path: '/sprint-4-audit'
      fullPath: '/sprint-4-audit'
      preLoaderRoute: typeof AuthenticatedSprint4AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-5-audit': {
      id: '/_authenticated/sprint-5-audit'
      path: '/sprint-5-audit'
      fullPath: '/sprint-5-audit'
      preLoaderRoute: typeof AuthenticatedSprint5AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ux-phase1-plan': {
      id: '/_authenticated/ux-phase1-plan'
      path: '/ux-phase1-plan'
      fullPath: '/ux-phase1-plan'
      preLoaderRoute: typeof AuthenticatedUxPhase1PlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/diagnostic/': {
      id: '/diagnostic/'
      path: '/diagnostic'
      fullPath: '/diagnostic/'
      preLoaderRoute: typeof DiagnosticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assessment/$assessmentId': {
      id: '/_authenticated/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners/$learnerId': {
      id: '/_authenticated/learners/$learnerId'
      path: '/$learnerId'
      fullPath: '/learners/$learnerId'
      preLoaderRoute: typeof AuthenticatedLearnersLearnerIdRouteImport
      parentRoute: typeof AuthenticatedLearnersRoute
    }
    '/_authenticated/session/$sessionId': {
      id: '/_authenticated/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/$sessionId': {
      id: '/_authenticated/tutor/$sessionId'
      path: '/tutor/$sessionId'
      fullPath: '/tutor/$sessionId'
      preLoaderRoute: typeof AuthenticatedTutorSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/diagnostic/checkout/$orderRef': {
      id: '/diagnostic/checkout/$orderRef'
      path: '/diagnostic/checkout/$orderRef'
      fullPath: '/diagnostic/checkout/$orderRef'
      preLoaderRoute: typeof DiagnosticCheckoutOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/report/$token': {
      id: '/diagnostic/report/$token'
      path: '/diagnostic/report/$token'
      fullPath: '/diagnostic/report/$token'
      preLoaderRoute: typeof DiagnosticReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/session/$token': {
      id: '/diagnostic/session/$token'
      path: '/diagnostic/session/$token'
      fullPath: '/diagnostic/session/$token'
      preLoaderRoute: typeof DiagnosticSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLearnersRouteChildren {
  AuthenticatedLearnersLearnerIdRoute: typeof AuthenticatedLearnersLearnerIdRoute
}

const AuthenticatedLearnersRouteChildren: AuthenticatedLearnersRouteChildren = {
  AuthenticatedLearnersLearnerIdRoute: AuthenticatedLearnersLearnerIdRoute,
}

const AuthenticatedLearnersRouteWithChildren =
  AuthenticatedLearnersRoute._addFileChildren(
    AuthenticatedLearnersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssessmentAuditRoute: typeof AuthenticatedAssessmentAuditRoute
  AuthenticatedAssessmentBlueprintRoute: typeof AuthenticatedAssessmentBlueprintRoute
  AuthenticatedAssessmentBlueprintAuditRoute: typeof AuthenticatedAssessmentBlueprintAuditRoute
  AuthenticatedAssessmentBuilderRoute: typeof AuthenticatedAssessmentBuilderRoute
  AuthenticatedAssessmentBuilderAuditRoute: typeof AuthenticatedAssessmentBuilderAuditRoute
  AuthenticatedAssessmentProofRoute: typeof AuthenticatedAssessmentProofRoute
  AuthenticatedAssessmentVerificationRoute: typeof AuthenticatedAssessmentVerificationRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedCurriculumAuditRoute: typeof AuthenticatedCurriculumAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticEngineRoute: typeof AuthenticatedDiagnosticEngineRoute
  AuthenticatedDiagnosticEngineAuditRoute: typeof AuthenticatedDiagnosticEngineAuditRoute
  AuthenticatedGapAnalysisRoute: typeof AuthenticatedGapAnalysisRoute
  AuthenticatedGapAnalysisAuditRoute: typeof AuthenticatedGapAnalysisAuditRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInterventionsRoute: typeof AuthenticatedInterventionsRoute
  AuthenticatedLaunchAuditRoute: typeof AuthenticatedLaunchAuditRoute
  AuthenticatedLearnersRoute: typeof AuthenticatedLearnersRouteWithChildren
  AuthenticatedOutcomeProofRoute: typeof AuthenticatedOutcomeProofRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedPilotEvidenceRoute: typeof AuthenticatedPilotEvidenceRoute
  AuthenticatedQuestionBankRoute: typeof AuthenticatedQuestionBankRoute
  AuthenticatedQuestionBankAuditRoute: typeof AuthenticatedQuestionBankAuditRoute
  AuthenticatedQuickStartRoute: typeof AuthenticatedQuickStartRoute
  AuthenticatedRlsVerificationRoute: typeof AuthenticatedRlsVerificationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSprint3AuditRoute: typeof AuthenticatedSprint3AuditRoute
  AuthenticatedSprint4AuditRoute: typeof AuthenticatedSprint4AuditRoute
  AuthenticatedSprint5AuditRoute: typeof AuthenticatedSprint5AuditRoute
  AuthenticatedUxPhase1PlanRoute: typeof AuthenticatedUxPhase1PlanRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedAssessmentAssessmentIdRoute: typeof AuthenticatedAssessmentAssessmentIdRoute
  AuthenticatedSessionSessionIdRoute: typeof AuthenticatedSessionSessionIdRoute
  AuthenticatedTutorSessionIdRoute: typeof AuthenticatedTutorSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssessmentAuditRoute: AuthenticatedAssessmentAuditRoute,
  AuthenticatedAssessmentBlueprintRoute: AuthenticatedAssessmentBlueprintRoute,
  AuthenticatedAssessmentBlueprintAuditRoute:
    AuthenticatedAssessmentBlueprintAuditRoute,
  AuthenticatedAssessmentBuilderRoute: AuthenticatedAssessmentBuilderRoute,
  AuthenticatedAssessmentBuilderAuditRoute:
    AuthenticatedAssessmentBuilderAuditRoute,
  AuthenticatedAssessmentProofRoute: AuthenticatedAssessmentProofRoute,
  AuthenticatedAssessmentVerificationRoute:
    AuthenticatedAssessmentVerificationRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedCurriculumAuditRoute: AuthenticatedCurriculumAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticEngineRoute: AuthenticatedDiagnosticEngineRoute,
  AuthenticatedDiagnosticEngineAuditRoute:
    AuthenticatedDiagnosticEngineAuditRoute,
  AuthenticatedGapAnalysisRoute: AuthenticatedGapAnalysisRoute,
  AuthenticatedGapAnalysisAuditRoute: AuthenticatedGapAnalysisAuditRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInterventionsRoute: AuthenticatedInterventionsRoute,
  AuthenticatedLaunchAuditRoute: AuthenticatedLaunchAuditRoute,
  AuthenticatedLearnersRoute: AuthenticatedLearnersRouteWithChildren,
  AuthenticatedOutcomeProofRoute: AuthenticatedOutcomeProofRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedPilotEvidenceRoute: AuthenticatedPilotEvidenceRoute,
  AuthenticatedQuestionBankRoute: AuthenticatedQuestionBankRoute,
  AuthenticatedQuestionBankAuditRoute: AuthenticatedQuestionBankAuditRoute,
  AuthenticatedQuickStartRoute: AuthenticatedQuickStartRoute,
  AuthenticatedRlsVerificationRoute: AuthenticatedRlsVerificationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSprint3AuditRoute: AuthenticatedSprint3AuditRoute,
  AuthenticatedSprint4AuditRoute: AuthenticatedSprint4AuditRoute,
  AuthenticatedSprint5AuditRoute: AuthenticatedSprint5AuditRoute,
  AuthenticatedUxPhase1PlanRoute: AuthenticatedUxPhase1PlanRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedAssessmentAssessmentIdRoute:
    AuthenticatedAssessmentAssessmentIdRoute,
  AuthenticatedSessionSessionIdRoute: AuthenticatedSessionSessionIdRoute,
  AuthenticatedTutorSessionIdRoute: AuthenticatedTutorSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DiagnosticIndexRoute: DiagnosticIndexRoute,
  DiagnosticCheckoutOrderRefRoute: DiagnosticCheckoutOrderRefRoute,
  DiagnosticReportTokenRoute: DiagnosticReportTokenRoute,
  DiagnosticSessionTokenRoute: DiagnosticSessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
