/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssessmentAuditRouteImport } from './routes/_authenticated/assessment-audit'
import { Route as AuthenticatedAssessmentProofRouteImport } from './routes/_authenticated/assessment-proof'
import { Route as AuthenticatedAssessmentVerificationRouteImport } from './routes/_authenticated/assessment-verification'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInterventionsRouteImport } from './routes/_authenticated/interventions'
import { Route as AuthenticatedLaunchAuditRouteImport } from './routes/_authenticated/launch-audit'
import { Route as AuthenticatedLearnersRouteImport } from './routes/_authenticated/learners'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedRlsVerificationRouteImport } from './routes/_authenticated/rls-verification'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSprint3AuditRouteImport } from './routes/_authenticated/sprint-3-audit'
import { Route as AuthenticatedSprint4AuditRouteImport } from './routes/_authenticated/sprint-4-audit'
import { Route as AuthenticatedSprint5AuditRouteImport } from './routes/_authenticated/sprint-5-audit'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedAssessmentAssessmentIdRouteImport } from './routes/_authenticated/assessment.$assessmentId'
import { Route as AuthenticatedLearnersLearnerIdRouteImport } from './routes/_authenticated/learners.$learnerId'
import { Route as AuthenticatedSessionSessionIdRouteImport } from './routes/_authenticated/session.$sessionId'
import { Route as AuthenticatedTutorSessionIdRouteImport } from './routes/_authenticated/tutor.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentAuditRoute =
  AuthenticatedAssessmentAuditRouteImport.update({
    id: '/assessment-audit',
    path: '/assessment-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentProofRoute =
  AuthenticatedAssessmentProofRouteImport.update({
    id: '/assessment-proof',
    path: '/assessment-proof',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentVerificationRoute =
  AuthenticatedAssessmentVerificationRouteImport.update({
    id: '/assessment-verification',
    path: '/assessment-verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterventionsRoute =
  AuthenticatedInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaunchAuditRoute =
  AuthenticatedLaunchAuditRouteImport.update({
    id: '/launch-audit',
    path: '/launch-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnersRoute = AuthenticatedLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRlsVerificationRoute =
  AuthenticatedRlsVerificationRouteImport.update({
    id: '/rls-verification',
    path: '/rls-verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSprint3AuditRoute =
  AuthenticatedSprint3AuditRouteImport.update({
    id: '/sprint-3-audit',
    path: '/sprint-3-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprint4AuditRoute =
  AuthenticatedSprint4AuditRouteImport.update({
    id: '/sprint-4-audit',
    path: '/sprint-4-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprint5AuditRoute =
  AuthenticatedSprint5AuditRouteImport.update({
    id: '/sprint-5-audit',
    path: '/sprint-5-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentAssessmentIdRoute =
  AuthenticatedAssessmentAssessmentIdRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnersLearnerIdRoute =
  AuthenticatedLearnersLearnerIdRouteImport.update({
    id: '/$learnerId',
    path: '/$learnerId',
    getParentRoute: () => AuthenticatedLearnersRoute,
  } as any)
const AuthenticatedSessionSessionIdRoute =
  AuthenticatedSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTutorSessionIdRoute =
  AuthenticatedTutorSessionIdRouteImport.update({
    id: '/tutor/$sessionId',
    path: '/tutor/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/parent': typeof AuthenticatedParentRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/parent': typeof AuthenticatedParentRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assessment-audit': typeof AuthenticatedAssessmentAuditRoute
  '/_authenticated/assessment-proof': typeof AuthenticatedAssessmentProofRoute
  '/_authenticated/assessment-verification': typeof AuthenticatedAssessmentVerificationRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/interventions': typeof AuthenticatedInterventionsRoute
  '/_authenticated/launch-audit': typeof AuthenticatedLaunchAuditRoute
  '/_authenticated/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sprint-3-audit': typeof AuthenticatedSprint3AuditRoute
  '/_authenticated/sprint-4-audit': typeof AuthenticatedSprint4AuditRoute
  '/_authenticated/sprint-5-audit': typeof AuthenticatedSprint5AuditRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/assessment/$assessmentId': typeof AuthenticatedAssessmentAssessmentIdRoute
  '/_authenticated/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/_authenticated/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/_authenticated/tutor/$sessionId': typeof AuthenticatedTutorSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/assessment-audit'
    | '/assessment-proof'
    | '/assessment-verification'
    | '/assessments'
    | '/assignments'
    | '/curriculum'
    | '/dashboard'
    | '/home'
    | '/interventions'
    | '/launch-audit'
    | '/learners'
    | '/parent'
    | '/rls-verification'
    | '/settings'
    | '/sprint-3-audit'
    | '/sprint-4-audit'
    | '/sprint-5-audit'
    | '/verification'
    | '/assessment/$assessmentId'
    | '/learners/$learnerId'
    | '/session/$sessionId'
    | '/tutor/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/assessment-audit'
    | '/assessment-proof'
    | '/assessment-verification'
    | '/assessments'
    | '/assignments'
    | '/curriculum'
    | '/dashboard'
    | '/home'
    | '/interventions'
    | '/launch-audit'
    | '/learners'
    | '/parent'
    | '/rls-verification'
    | '/settings'
    | '/sprint-3-audit'
    | '/sprint-4-audit'
    | '/sprint-5-audit'
    | '/verification'
    | '/assessment/$assessmentId'
    | '/learners/$learnerId'
    | '/session/$sessionId'
    | '/tutor/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/assessment-audit'
    | '/_authenticated/assessment-proof'
    | '/_authenticated/assessment-verification'
    | '/_authenticated/assessments'
    | '/_authenticated/assignments'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/interventions'
    | '/_authenticated/launch-audit'
    | '/_authenticated/learners'
    | '/_authenticated/parent'
    | '/_authenticated/rls-verification'
    | '/_authenticated/settings'
    | '/_authenticated/sprint-3-audit'
    | '/_authenticated/sprint-4-audit'
    | '/_authenticated/sprint-5-audit'
    | '/_authenticated/verification'
    | '/_authenticated/assessment/$assessmentId'
    | '/_authenticated/learners/$learnerId'
    | '/_authenticated/session/$sessionId'
    | '/_authenticated/tutor/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-audit': {
      id: '/_authenticated/assessment-audit'
      path: '/assessment-audit'
      fullPath: '/assessment-audit'
      preLoaderRoute: typeof AuthenticatedAssessmentAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-proof': {
      id: '/_authenticated/assessment-proof'
      path: '/assessment-proof'
      fullPath: '/assessment-proof'
      preLoaderRoute: typeof AuthenticatedAssessmentProofRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-verification': {
      id: '/_authenticated/assessment-verification'
      path: '/assessment-verification'
      fullPath: '/assessment-verification'
      preLoaderRoute: typeof AuthenticatedAssessmentVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interventions': {
      id: '/_authenticated/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthenticatedInterventionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/launch-audit': {
      id: '/_authenticated/launch-audit'
      path: '/launch-audit'
      fullPath: '/launch-audit'
      preLoaderRoute: typeof AuthenticatedLaunchAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners': {
      id: '/_authenticated/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof AuthenticatedLearnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rls-verification': {
      id: '/_authenticated/rls-verification'
      path: '/rls-verification'
      fullPath: '/rls-verification'
      preLoaderRoute: typeof AuthenticatedRlsVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-3-audit': {
      id: '/_authenticated/sprint-3-audit'
      path: '/sprint-3-audit'
      fullPath: '/sprint-3-audit'
      preLoaderRoute: typeof AuthenticatedSprint3AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-4-audit': {
      id: '/_authenticated/sprint-4-audit'
      path: '/sprint-4-audit'
      fullPath: '/sprint-4-audit'
      preLoaderRoute: typeof AuthenticatedSprint4AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprint-5-audit': {
      id: '/_authenticated/sprint-5-audit'
      path: '/sprint-5-audit'
      fullPath: '/sprint-5-audit'
      preLoaderRoute: typeof AuthenticatedSprint5AuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment/$assessmentId': {
      id: '/_authenticated/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners/$learnerId': {
      id: '/_authenticated/learners/$learnerId'
      path: '/$learnerId'
      fullPath: '/learners/$learnerId'
      preLoaderRoute: typeof AuthenticatedLearnersLearnerIdRouteImport
      parentRoute: typeof AuthenticatedLearnersRoute
    }
    '/_authenticated/session/$sessionId': {
      id: '/_authenticated/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/$sessionId': {
      id: '/_authenticated/tutor/$sessionId'
      path: '/tutor/$sessionId'
      fullPath: '/tutor/$sessionId'
      preLoaderRoute: typeof AuthenticatedTutorSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedLearnersRouteChildren {
  AuthenticatedLearnersLearnerIdRoute: typeof AuthenticatedLearnersLearnerIdRoute
}

const AuthenticatedLearnersRouteChildren: AuthenticatedLearnersRouteChildren = {
  AuthenticatedLearnersLearnerIdRoute: AuthenticatedLearnersLearnerIdRoute,
}

const AuthenticatedLearnersRouteWithChildren =
  AuthenticatedLearnersRoute._addFileChildren(
    AuthenticatedLearnersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssessmentAuditRoute: typeof AuthenticatedAssessmentAuditRoute
  AuthenticatedAssessmentProofRoute: typeof AuthenticatedAssessmentProofRoute
  AuthenticatedAssessmentVerificationRoute: typeof AuthenticatedAssessmentVerificationRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInterventionsRoute: typeof AuthenticatedInterventionsRoute
  AuthenticatedLaunchAuditRoute: typeof AuthenticatedLaunchAuditRoute
  AuthenticatedLearnersRoute: typeof AuthenticatedLearnersRouteWithChildren
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedRlsVerificationRoute: typeof AuthenticatedRlsVerificationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSprint3AuditRoute: typeof AuthenticatedSprint3AuditRoute
  AuthenticatedSprint4AuditRoute: typeof AuthenticatedSprint4AuditRoute
  AuthenticatedSprint5AuditRoute: typeof AuthenticatedSprint5AuditRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedAssessmentAssessmentIdRoute: typeof AuthenticatedAssessmentAssessmentIdRoute
  AuthenticatedSessionSessionIdRoute: typeof AuthenticatedSessionSessionIdRoute
  AuthenticatedTutorSessionIdRoute: typeof AuthenticatedTutorSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssessmentAuditRoute: AuthenticatedAssessmentAuditRoute,
  AuthenticatedAssessmentProofRoute: AuthenticatedAssessmentProofRoute,
  AuthenticatedAssessmentVerificationRoute:
    AuthenticatedAssessmentVerificationRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInterventionsRoute: AuthenticatedInterventionsRoute,
  AuthenticatedLaunchAuditRoute: AuthenticatedLaunchAuditRoute,
  AuthenticatedLearnersRoute: AuthenticatedLearnersRouteWithChildren,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedRlsVerificationRoute: AuthenticatedRlsVerificationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSprint3AuditRoute: AuthenticatedSprint3AuditRoute,
  AuthenticatedSprint4AuditRoute: AuthenticatedSprint4AuditRoute,
  AuthenticatedSprint5AuditRoute: AuthenticatedSprint5AuditRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedAssessmentAssessmentIdRoute:
    AuthenticatedAssessmentAssessmentIdRoute,
  AuthenticatedSessionSessionIdRoute: AuthenticatedSessionSessionIdRoute,
  AuthenticatedTutorSessionIdRoute: AuthenticatedTutorSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
