-- Forward-only staging reconciliation (generated by scripts/db/generate-reconciliation-migration.py)
--
-- Purpose: make a database that followed the staging history (full
-- 20260915161655 remediation DDL, the hardened PR #5 20261002052550, the
-- renamed 20260905100552/100631/100711 copies) converge on canonical main's
-- schema WITHOUT touching any applied migration and WITHOUT deleting or
-- overwriting a single row. Every statement is idempotent:
--   CREATE TABLE/INDEX ... IF NOT EXISTS, policies and triggers created only
--   when absent, views CREATE OR REPLACE, functions CREATE OR REPLACE,
--   inserts ON CONFLICT DO NOTHING, grants/revokes re-asserted.
-- On a database that already followed main this migration is a no-op.
-- It never DROPs a table or column, never TRUNCATEs, never DELETEs.
--
-- It does NOT and cannot mark main-only migration names as applied on
-- staging; that is a migration-ledger operation (see
-- verification/staging-migration-reconciliation/VERIFICATION_REPORT.md).


-- ===== from 20260919175712_8a16e7d2-73e0-40d7-908e-d07bd538e2fa.sql =====
DO $do$
BEGIN
  IF to_regclass('public.feedback_submissions') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.feedback_submissions FROM anon, authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.guidance_events') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.guidance_events FROM anon, authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.feedback_submissions') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.feedback_submissions TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.guidance_events') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.guidance_events TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.pilot_invitations') IS NOT NULL THEN
    EXECUTE $guard$REVOKE SELECT ON public.pilot_invitations FROM anon$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.remediation_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  label text NOT NULL,
  scope text NOT NULL,
  checksum text NOT NULL,
  location text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
DO $do$
BEGIN
  IF to_regclass('public.remediation_snapshots') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.remediation_snapshots TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_snapshots') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.remediation_snapshots TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_snapshots') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.remediation_snapshots ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'remediation_snapshots' AND policyname = 'remediation_snapshots_select') THEN
    EXECUTE $guard$CREATE POLICY "remediation_snapshots_select" ON public.remediation_snapshots
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND private.has_role(auth.uid(), 'admin'::app_role))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.remediation_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  run_id uuid NOT NULL,
  action_type text NOT NULL,
  question_id uuid,
  external_ref text,
  subject text,
  prior_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  new_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  reason text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS remediation_actions_run_idx ON public.remediation_actions (run_id, created_at);
CREATE INDEX IF NOT EXISTS remediation_actions_question_idx ON public.remediation_actions (question_id);
DO $do$
BEGIN
  IF to_regclass('public.remediation_actions') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.remediation_actions TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_actions') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.remediation_actions TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_actions') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.remediation_actions ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'remediation_actions' AND policyname = 'remediation_actions_select') THEN
    EXECUTE $guard$CREATE POLICY "remediation_actions_select" ON public.remediation_actions
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE FUNCTION public.remediation_append_only()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'remediation_actions' AND t.tgname = 'remediation_actions_no_update' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER remediation_actions_no_update BEFORE UPDATE ON public.remediation_actions
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'remediation_actions' AND t.tgname = 'remediation_actions_no_delete' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER remediation_actions_no_delete BEFORE DELETE ON public.remediation_actions
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.remediation_work_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  ref text NOT NULL UNIQUE,
  title text NOT NULL,
  severity text NOT NULL DEFAULT 'P0',
  status text NOT NULL DEFAULT 'open',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DO $do$
BEGIN
  IF to_regclass('public.remediation_work_items') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.remediation_work_items TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_work_items') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.remediation_work_items TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_work_items') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.remediation_work_items ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'remediation_work_items' AND policyname = 'remediation_work_items_select') THEN
    EXECUTE $guard$CREATE POLICY "remediation_work_items_select" ON public.remediation_work_items
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'remediation_work_items' AND t.tgname = 'touch_remediation_work_items' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER touch_remediation_work_items BEFORE UPDATE ON public.remediation_work_items
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.question_pool_exclusions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  pool text NOT NULL,
  reason text NOT NULL,
  work_item_ref text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (question_id, pool)
);
CREATE INDEX IF NOT EXISTS question_pool_exclusions_pool_idx ON public.question_pool_exclusions (pool, active);
DO $do$
BEGIN
  IF to_regclass('public.question_pool_exclusions') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.question_pool_exclusions TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_pool_exclusions') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.question_pool_exclusions TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_pool_exclusions') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.question_pool_exclusions ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'question_pool_exclusions' AND policyname = 'question_pool_exclusions_select') THEN
    EXECUTE $guard$CREATE POLICY "question_pool_exclusions_select" ON public.question_pool_exclusions
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'question_pool_exclusions' AND t.tgname = 'touch_question_pool_exclusions' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER touch_question_pool_exclusions BEFORE UPDATE ON public.question_pool_exclusions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.sme_review_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  subject text NOT NULL,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  routing_reason text NOT NULL,
  priority integer NOT NULL DEFAULT 100,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  queued_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (question_id, routing_reason),
  CONSTRAINT sme_review_queue_subject_check CHECK (subject IN ('Mathematics', 'Science'))
);
CREATE INDEX IF NOT EXISTS sme_review_queue_subject_idx ON public.sme_review_queue (subject, priority, queued_at);
DO $do$
BEGIN
  IF to_regclass('public.sme_review_queue') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.sme_review_queue TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.sme_review_queue') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.sme_review_queue TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.sme_review_queue') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.sme_review_queue ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'sme_review_queue' AND policyname = 'sme_review_queue_select') THEN
    EXECUTE $guard$CREATE POLICY "sme_review_queue_select" ON public.sme_review_queue
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.legacy_verification_quarantine (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  legacy_database_id uuid NOT NULL,
  external_ref text,
  subject text NOT NULL,
  legacy_status text NOT NULL,
  legacy_verified_at timestamptz,
  legacy_verification_note text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  quarantined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (legacy_database_id)
);
DO $do$
BEGIN
  IF to_regclass('public.legacy_verification_quarantine') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.legacy_verification_quarantine TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.legacy_verification_quarantine') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.legacy_verification_quarantine TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.legacy_verification_quarantine') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.legacy_verification_quarantine ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'legacy_verification_quarantine' AND policyname = 'legacy_verification_quarantine_select') THEN
    EXECUTE $guard$CREATE POLICY "legacy_verification_quarantine_select" ON public.legacy_verification_quarantine
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'legacy_verification_quarantine' AND t.tgname = 'legacy_quarantine_no_update' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER legacy_quarantine_no_update BEFORE UPDATE ON public.legacy_verification_quarantine
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'legacy_verification_quarantine' AND t.tgname = 'legacy_quarantine_no_delete' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER legacy_quarantine_no_delete BEFORE DELETE ON public.legacy_verification_quarantine
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.engine_rerun_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  run_id uuid NOT NULL,
  engine_version text NOT NULL,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  outcome text NOT NULL,
  confidence numeric NOT NULL DEFAULT 0,
  strong_signals integer NOT NULL DEFAULT 0,
  checks jsonb NOT NULL DEFAULT '[]'::jsonb,
  reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (run_id, question_id),
  CONSTRAINT engine_rerun_results_outcome_check CHECK (outcome IN ('auto_approved', 'quarantined'))
);
CREATE INDEX IF NOT EXISTS engine_rerun_results_run_idx ON public.engine_rerun_results (run_id);
DO $do$
BEGIN
  IF to_regclass('public.engine_rerun_results') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.engine_rerun_results TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.engine_rerun_results') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.engine_rerun_results TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.engine_rerun_results') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.engine_rerun_results ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'engine_rerun_results' AND policyname = 'engine_rerun_results_select') THEN
    EXECUTE $guard$CREATE POLICY "engine_rerun_results_select" ON public.engine_rerun_results
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'engine_rerun_results' AND t.tgname = 'engine_rerun_results_no_update' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER engine_rerun_results_no_update BEFORE UPDATE ON public.engine_rerun_results
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'engine_rerun_results' AND t.tgname = 'engine_rerun_results_no_delete' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER engine_rerun_results_no_delete BEFORE DELETE ON public.engine_rerun_results
  FOR EACH ROW EXECUTE FUNCTION public.remediation_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.engine_rerun_results') IS NOT NULL THEN
    EXECUTE $guard$DROP TRIGGER IF EXISTS engine_rerun_results_no_delete ON public.engine_rerun_results$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.legacy_verification_quarantine') IS NOT NULL THEN
    EXECUTE $guard$DROP TRIGGER IF EXISTS legacy_quarantine_no_delete ON public.legacy_verification_quarantine$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE FUNCTION public.auto_verifications_immutable()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF TG_OP = 'DELETE' AND current_user IN ('service_role', 'postgres', 'supabase_admin') THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'Automated verification records are append-only';
END;
$function$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_actions') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.remediation_actions FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.engine_rerun_results') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.engine_rerun_results FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.sme_review_queue') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.sme_review_queue FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_pool_exclusions') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.question_pool_exclusions FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.legacy_verification_quarantine') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.legacy_verification_quarantine FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_work_items') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.remediation_work_items FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.remediation_snapshots') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.remediation_snapshots FROM anon$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.automated_review_imports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  package_name text NOT NULL,
  package_sha256 text NOT NULL,
  package_bytes bigint NOT NULL,
  generator_run_hash text NOT NULL,
  validator_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision_class text NOT NULL DEFAULT 'FOUNDER_AUTHORIZED_AUTOMATED_PROVISIONAL',
  founder_authorized boolean NOT NULL DEFAULT true,
  is_human_sme_decision boolean NOT NULL DEFAULT false,
  counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  state text NOT NULL DEFAULT 'active',
  rolled_back_at timestamptz,
  imported_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT automated_review_imports_class_chk
    CHECK (decision_class = 'FOUNDER_AUTHORIZED_AUTOMATED_PROVISIONAL'),
  CONSTRAINT automated_review_imports_not_human_chk CHECK (is_human_sme_decision = false),
  CONSTRAINT automated_review_imports_state_chk CHECK (state IN ('active','rolled_back'))
);
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_review_imports TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_review_imports TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.automated_review_imports ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'automated_review_imports' AND policyname = 'automated_review_imports_select') THEN
    EXECUTE $guard$CREATE POLICY "automated_review_imports_select" ON public.automated_review_imports
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.automated_provisional_outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  import_id uuid NOT NULL REFERENCES public.automated_review_imports(id) ON DELETE RESTRICT,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  queue_row_key text NOT NULL,
  queue_routing_id uuid REFERENCES public.sme_review_queue(id) ON DELETE SET NULL,
  queue_routing_reason text NOT NULL,
  item_version_updated_at timestamptz NOT NULL,
  content_sha256 text NOT NULL,
  provisional_outcome text NOT NULL,
  is_question_level_primary boolean NOT NULL DEFAULT true,
  pass_a_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  pass_b_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  pass_c_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  checks_executed jsonb NOT NULL DEFAULT '[]'::jsonb,
  checks_not_executed jsonb NOT NULL DEFAULT '[]'::jsonb,
  engine_outcome text,
  engine_version text,
  package_sha256 text NOT NULL,
  generator_run_hash text NOT NULL,
  validator_passed boolean NOT NULL,
  decision_class text NOT NULL DEFAULT 'FOUNDER_AUTHORIZED_AUTOMATED_PROVISIONAL',
  founder_authorized boolean NOT NULL DEFAULT true,
  automated_not_human boolean NOT NULL DEFAULT true,
  reviewer_identity text,
  reviewer_qualification text,
  human_signature text,
  advisory_note text,
  import_operation_id text NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now(),
  superseded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT apo_subject_chk CHECK (subject IN ('Mathematics','Science')),
  CONSTRAINT apo_outcome_chk CHECK (provisional_outcome IN (
    'AUTOMATED_PROVISIONAL_PASS',
    'AUTOMATED_PROVISIONAL_PASS_WITH_METADATA_FIX',
    'AUTOMATED_PROVISIONAL_CONTENT_FIX',
    'AUTOMATED_PROVISIONAL_REPLACEMENT',
    'AUTOMATED_PROVISIONAL_REJECT',
    'AUTOMATED_UNRESOLVED')),
  CONSTRAINT apo_class_chk CHECK (decision_class = 'FOUNDER_AUTHORIZED_AUTOMATED_PROVISIONAL'),
  CONSTRAINT apo_not_human_chk CHECK (
    automated_not_human = true
    AND reviewer_identity IS NULL
    AND reviewer_qualification IS NULL
    AND human_signature IS NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS apo_active_queue_row_uniq
  ON public.automated_provisional_outcomes (queue_row_key, package_sha256)
  WHERE superseded_at IS NULL;
CREATE INDEX IF NOT EXISTS apo_question_idx ON public.automated_provisional_outcomes (question_id);
CREATE INDEX IF NOT EXISTS apo_import_idx ON public.automated_provisional_outcomes (import_id);
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_provisional_outcomes TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_provisional_outcomes TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.automated_provisional_outcomes ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'automated_provisional_outcomes' AND policyname = 'automated_provisional_outcomes_select') THEN
    EXECUTE $guard$CREATE POLICY "automated_provisional_outcomes_select" ON public.automated_provisional_outcomes
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE FUNCTION public.automated_provisional_outcomes_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'automated_provisional_outcomes is append-only';
  END IF;
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.question_id IS DISTINCT FROM OLD.question_id
     OR NEW.queue_row_key IS DISTINCT FROM OLD.queue_row_key
     OR NEW.provisional_outcome IS DISTINCT FROM OLD.provisional_outcome
     OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
     OR NEW.package_sha256 IS DISTINCT FROM OLD.package_sha256
     OR NEW.pass_a_evidence IS DISTINCT FROM OLD.pass_a_evidence
     OR NEW.pass_b_evidence IS DISTINCT FROM OLD.pass_b_evidence
     OR NEW.pass_c_evidence IS DISTINCT FROM OLD.pass_c_evidence
     OR NEW.import_operation_id IS DISTINCT FROM OLD.import_operation_id THEN
    RAISE EXCEPTION 'automated_provisional_outcomes evidence is immutable; only superseded_at may change';
  END IF;
  RETURN NEW;
END;
$$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'automated_provisional_outcomes' AND t.tgname = 'apo_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER apo_append_only
  BEFORE UPDATE OR DELETE ON public.automated_provisional_outcomes
  FOR EACH ROW EXECUTE FUNCTION public.automated_provisional_outcomes_append_only()$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.automated_review_rollback_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  import_id uuid REFERENCES public.automated_review_imports(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  package_sha256 text NOT NULL,
  affected_rows integer NOT NULL DEFAULT 0,
  state_hash text,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arre_event_chk CHECK (event_type IN ('ROLLBACK','REAPPLY','IDEMPOTENCY_TEST'))
);
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_review_rollback_events TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_review_rollback_events TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.automated_review_rollback_events ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'automated_review_rollback_events' AND policyname = 'automated_review_rollback_events_select') THEN
    EXECUTE $guard$CREATE POLICY "automated_review_rollback_events_select" ON public.automated_review_rollback_events
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE FUNCTION public.automated_review_rollback_events_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'automated_review_rollback_events is append-only';
END;
$$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'automated_review_rollback_events' AND t.tgname = 'arre_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER arre_append_only
  BEFORE UPDATE OR DELETE ON public.automated_review_rollback_events
  FOR EACH ROW EXECUTE FUNCTION public.automated_review_rollback_events_append_only()$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE VIEW public.automated_provisional_question_outcomes
WITH (security_invoker = true) AS
SELECT
  o.org_id,
  o.question_id,
  max(o.external_ref) AS external_ref,
  max(o.subject) AS subject,
  count(*) AS queue_rows,
  min(o.provisional_outcome) AS provisional_outcome,
  bool_and(o.automated_not_human) AS automated_not_human,
  max(o.decision_class) AS decision_class,
  max(o.package_sha256) AS package_sha256,
  max(o.imported_at) AS imported_at
FROM public.automated_provisional_outcomes o
WHERE o.superseded_at IS NULL
GROUP BY o.org_id, o.question_id;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_provisional_question_outcomes TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_provisional_question_outcomes TO service_role$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE VIEW public.internal_automated_provisional_pool
WITH (security_invoker = true) AS
SELECT
  q.org_id,
  q.question_id,
  q.external_ref,
  q.subject,
  q.provisional_outcome,
  'INTERNAL_AUTOMATED_PROVISIONAL'::text AS pool_label,
  false AS paid_selection_eligible,
  false AS production_export_eligible
FROM public.automated_provisional_question_outcomes q
WHERE q.provisional_outcome = 'AUTOMATED_PROVISIONAL_PASS';
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.internal_automated_provisional_pool TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.internal_automated_provisional_pool TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'automated_review_imports' AND t.tgname = 'automated_review_imports_touch' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER automated_review_imports_touch
  BEFORE UPDATE ON public.automated_review_imports
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_review_imports FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_provisional_outcomes FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_review_rollback_events FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_provisional_question_outcomes FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.internal_automated_provisional_pool FROM anon$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_review_imports FROM authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_provisional_outcomes FROM authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_review_rollback_events FROM authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.automated_provisional_question_outcomes FROM authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$REVOKE ALL ON public.internal_automated_provisional_pool FROM authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_review_imports TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_provisional_outcomes TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_review_rollback_events TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.automated_provisional_question_outcomes TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.internal_automated_provisional_pool TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_imports') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_review_imports TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_provisional_outcomes TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_review_rollback_events') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_review_rollback_events TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.automated_provisional_question_outcomes') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.automated_provisional_question_outcomes TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.internal_automated_provisional_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.internal_automated_provisional_pool TO service_role$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.question_marking_specs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  spec_version integer NOT NULL DEFAULT 1,
  content_sha256 text NOT NULL,
  expected_conclusion text NOT NULL,
  required_reasoning jsonb NOT NULL DEFAULT '[]'::jsonb,
  acceptable_equivalents jsonb NOT NULL DEFAULT '[]'::jsonb,
  terminology jsonb NOT NULL DEFAULT '[]'::jsonb,
  units text,
  tolerance jsonb,
  common_mistakes jsonb NOT NULL DEFAULT '[]'::jsonb,
  minimum_passing_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  spec_sha256 text NOT NULL,
  authored_by text NOT NULL DEFAULT 'AUTOMATED_FOUNDER_AUTHORIZED',
  human_signature text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (question_id, spec_version)
);
DO $do$
BEGIN
  IF to_regclass('public.question_marking_specs') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.question_marking_specs TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_marking_specs') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.question_marking_specs TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_marking_specs') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.question_marking_specs ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'question_marking_specs' AND policyname = 'question_marking_specs_select') THEN
    EXECUTE $guard$CREATE POLICY "question_marking_specs_select" ON public.question_marking_specs
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.question_content_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  revision_reason text NOT NULL,
  revision_kind text NOT NULL,
  before_content jsonb NOT NULL,
  after_content jsonb NOT NULL,
  before_sha256 text NOT NULL,
  after_sha256 text NOT NULL,
  applied boolean NOT NULL DEFAULT false,
  rolled_back_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
DO $do$
BEGIN
  IF to_regclass('public.question_content_revisions') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.question_content_revisions TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_content_revisions') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.question_content_revisions TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_content_revisions') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.question_content_revisions ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'question_content_revisions' AND policyname = 'question_content_revisions_select') THEN
    EXECUTE $guard$CREATE POLICY "question_content_revisions_select" ON public.question_content_revisions
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.curriculum_source_register (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  source_title text NOT NULL,
  source_url text,
  section_ref text,
  accessed_at date,
  checksum_sha256 text,
  alignment_note text,
  licence_status text NOT NULL DEFAULT 'NOT_ASSESSED',
  verbatim_copying boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (question_id, source_title, section_ref)
);
DO $do$
BEGIN
  IF to_regclass('public.curriculum_source_register') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.curriculum_source_register TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.curriculum_source_register') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.curriculum_source_register TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.curriculum_source_register') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.curriculum_source_register ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'curriculum_source_register' AND policyname = 'curriculum_source_register_select') THEN
    EXECUTE $guard$CREATE POLICY "curriculum_source_register_select" ON public.curriculum_source_register
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.question_originality_checks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  revision_id uuid REFERENCES public.question_content_revisions(id) ON DELETE SET NULL,
  matched_shingle text,
  exact_match boolean NOT NULL,
  normalized_match boolean NOT NULL,
  max_shingle_overlap numeric NOT NULL,
  semantic_similarity numeric NOT NULL,
  verdict text NOT NULL,
  copyright_clearance_claimed boolean NOT NULL DEFAULT false,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
DO $do$
BEGIN
  IF to_regclass('public.question_originality_checks') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.question_originality_checks TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_originality_checks') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.question_originality_checks TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_originality_checks') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.question_originality_checks ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'question_originality_checks' AND policyname = 'question_originality_checks_select') THEN
    EXECUTE $guard$CREATE POLICY "question_originality_checks_select" ON public.question_originality_checks
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
CREATE OR REPLACE FUNCTION public.content_resolution_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND TG_TABLE_NAME = 'question_content_revisions' THEN
    IF NEW.id IS NOT DISTINCT FROM OLD.id
       AND NEW.question_id IS NOT DISTINCT FROM OLD.question_id
       AND NEW.before_content IS NOT DISTINCT FROM OLD.before_content
       AND NEW.after_content IS NOT DISTINCT FROM OLD.after_content
       AND NEW.before_sha256 IS NOT DISTINCT FROM OLD.before_sha256
       AND NEW.after_sha256 IS NOT DISTINCT FROM OLD.after_sha256 THEN
      RETURN NEW;
    END IF;
  END IF;
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'question_marking_specs' AND t.tgname = 'question_marking_specs_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER question_marking_specs_append_only
  BEFORE UPDATE OR DELETE ON public.question_marking_specs
  FOR EACH ROW EXECUTE FUNCTION public.content_resolution_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'question_content_revisions' AND t.tgname = 'question_content_revisions_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER question_content_revisions_append_only
  BEFORE UPDATE OR DELETE ON public.question_content_revisions
  FOR EACH ROW EXECUTE FUNCTION public.content_resolution_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'curriculum_source_register' AND t.tgname = 'curriculum_source_register_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER curriculum_source_register_append_only
  BEFORE UPDATE OR DELETE ON public.curriculum_source_register
  FOR EACH ROW EXECUTE FUNCTION public.content_resolution_append_only()$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'question_originality_checks' AND t.tgname = 'question_originality_checks_append_only' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER question_originality_checks_append_only
  BEFORE UPDATE OR DELETE ON public.question_originality_checks
  FOR EACH ROW EXECUTE FUNCTION public.content_resolution_append_only()$guard$;
  END IF;
END
$do$;
CREATE INDEX IF NOT EXISTS idx_marking_specs_question ON public.question_marking_specs(question_id);
CREATE INDEX IF NOT EXISTS idx_content_revisions_question ON public.question_content_revisions(question_id);
CREATE INDEX IF NOT EXISTS idx_source_register_question ON public.curriculum_source_register(question_id);
CREATE INDEX IF NOT EXISTS idx_originality_checks_question ON public.question_originality_checks(question_id);

-- ===== from 20260919175907_a6cec947-baea-4506-9661-db7cef48a32a.sql =====
INSERT INTO public.question_pool_exclusions (org_id, question_id, external_ref, pool, reason, work_item_ref, active)
SELECT q.org_id, q.id, q.external_ref, 'paid',
  'Engine v1.0.0 quarantined; no named-SME approval. Not eligible for paid selection.',
  NULL, true
FROM public.question_bank q
JOIN public.question_auto_verifications av ON av.question_id = q.id AND av.outcome = 'quarantined'
ON CONFLICT (question_id, pool) DO NOTHING;
INSERT INTO public.remediation_work_items (org_id, ref, title, severity, status, details)
SELECT q.org_id, 'REASSESSMENT-146ec7c8-POOL-BREACH', 'Published reassessment 146ec7c8 served diagnostic-pool items (REQ001-DIAG-001/005/009)', 'P0', 'open',
  jsonb_build_object(
    'reassessment_id','146ec7c8',
    'requirements', jsonb_build_array('REQ001-DIAG-001','REQ001-DIAG-005','REQ001-DIAG-009'),
    'external_refs', jsonb_build_array('C10-2627-MATH-REQ001-DIAG-001','C10-2627-MATH-REQ001-DIAG-005','C10-2627-MATH-REQ001-DIAG-009'),
    'condition','C1',
    'action_taken','excluded from paid diagnostic capacity in production',
    'not_done', jsonb_build_array('no deletion','no silent pool reclassification'),
    'resolution_required_before','paid diagnostic reuse')
FROM public.question_bank q
WHERE q.external_ref = 'C10-2627-MATH-REQ001-DIAG-001'
ON CONFLICT (ref) DO NOTHING;
INSERT INTO public.question_pool_exclusions (org_id, question_id, external_ref, pool, reason, work_item_ref, active)
SELECT q.org_id, q.id, q.external_ref, 'paid_diagnostic',
  'C1: served inside published reassessment 146ec7c8; excluded from paid diagnostic capacity until the pool breach is resolved.',
  'REASSESSMENT-146ec7c8-POOL-BREACH', true
FROM public.question_bank q
WHERE q.external_ref IN ('C10-2627-MATH-REQ001-DIAG-001','C10-2627-MATH-REQ001-DIAG-005','C10-2627-MATH-REQ001-DIAG-009')
ON CONFLICT (question_id, pool) DO NOTHING;

-- ===== from 20260919195620_b30e9647-5517-4603-9c1c-6d244ee2c4b3.sql =====
CREATE TABLE IF NOT EXISTS public.question_commercial_release (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organizations(id),
  question_id uuid NOT NULL REFERENCES public.question_bank(id) ON DELETE CASCADE,
  external_ref text,
  subject text NOT NULL,
  release_basis text NOT NULL DEFAULT 'FOUNDER_APPROVED_AUTOMATED_PRODUCTION',
  commercial_classification text NOT NULL,
  classification_basis text NOT NULL,
  content_sha256 text NOT NULL,
  engine_version text NOT NULL,
  activation_run_id uuid NOT NULL,
  paid_selection_eligible boolean NOT NULL DEFAULT false,
  production_export_eligible boolean NOT NULL DEFAULT false,
  human_sme_certified boolean NOT NULL DEFAULT false,
  official_cbse_ncert_certified boolean NOT NULL DEFAULT false,
  copyright_permission_claimed boolean NOT NULL DEFAULT false,
  automated_not_human boolean NOT NULL DEFAULT true,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  activated_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT qcr_basis_chk CHECK (release_basis = 'FOUNDER_APPROVED_AUTOMATED_PRODUCTION'),
  CONSTRAINT qcr_class_chk CHECK (commercial_classification = ANY (ARRAY[
    'ORIGINAL_EDUOS_CONTENT','FACT_OR_FORMULA_ONLY','EXPLICITLY_OPEN_LICENSED',
    'PERMISSION_DOCUMENTED','COMMERCIAL_USE_BLOCKED'])),
  CONSTRAINT qcr_no_human_cert_chk CHECK (human_sme_certified = false),
  CONSTRAINT qcr_no_official_cert_chk CHECK (official_cbse_ncert_certified = false),
  CONSTRAINT qcr_no_copyright_claim_chk CHECK (copyright_permission_claimed = false),
  CONSTRAINT qcr_not_human_chk CHECK (automated_not_human = true),
  CONSTRAINT qcr_blocked_not_eligible_chk CHECK (
    commercial_classification <> 'COMMERCIAL_USE_BLOCKED'
    OR (paid_selection_eligible = false AND production_export_eligible = false)),
  CONSTRAINT qcr_question_run_key UNIQUE (question_id, activation_run_id)
);
DO $do$
BEGIN
  IF to_regclass('public.question_commercial_release') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.question_commercial_release TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_commercial_release') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.question_commercial_release TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.question_commercial_release') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.question_commercial_release ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'question_commercial_release' AND policyname = 'qcr_select_staff') THEN
    EXECUTE $guard$CREATE POLICY "qcr_select_staff" ON public.question_commercial_release
  FOR SELECT TO authenticated
  USING (org_id = private.current_org_id() AND (private.is_staff() OR private.is_reviewer()))$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'question_commercial_release' AND t.tgname = 'touch_question_commercial_release' AND NOT t.tgisinternal) THEN
    EXECUTE $guard$CREATE TRIGGER touch_question_commercial_release
  BEFORE UPDATE ON public.question_commercial_release
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()$guard$;
  END IF;
END
$do$;
CREATE INDEX IF NOT EXISTS idx_qcr_question ON public.question_commercial_release (question_id);
CREATE INDEX IF NOT EXISTS idx_qcr_active ON public.question_commercial_release (org_id) WHERE revoked_at IS NULL;
CREATE OR REPLACE VIEW public.production_release_pool AS
  SELECT r.org_id,
         r.question_id,
         r.external_ref,
         r.subject,
         r.release_basis,
         r.commercial_classification,
         r.content_sha256,
         r.paid_selection_eligible,
         r.production_export_eligible
  FROM public.question_commercial_release r
  WHERE r.revoked_at IS NULL
    AND r.paid_selection_eligible = true
    AND NOT EXISTS (
      SELECT 1 FROM public.question_pool_exclusions e
      WHERE e.question_id = r.question_id AND e.active = true
    );
DO $do$
BEGIN
  IF to_regclass('public.production_release_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.production_release_pool TO authenticated$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.production_release_pool') IS NOT NULL THEN
    EXECUTE $guard$GRANT SELECT ON public.production_release_pool TO service_role$guard$;
  END IF;
END
$do$;

-- ===== from 20260919195651_fdde1774-86cb-44f5-9172-ac6398190072.sql =====
DO $do$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_views WHERE schemaname = 'public' AND viewname = 'production_release_pool') THEN
    EXECUTE $guard$ALTER VIEW public.production_release_pool SET (security_invoker = on)$guard$;
  END IF;
END
$do$;

-- ===== from 20261002045629_be60915e-3ad8-4dbe-9bbb-314f7edca414.sql =====
DO $do$
BEGIN
  IF to_regclass('public.pilot_leads') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.pilot_leads ADD COLUMN IF NOT EXISTS owner_notified_at timestamptz$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.pilot_leads') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.pilot_leads ADD COLUMN IF NOT EXISTS owner_notification_error text$guard$;
  END IF;
END
$do$;
CREATE TABLE IF NOT EXISTS public.founder_access_denials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid,
  operation text NOT NULL CHECK (length(operation) <= 80),
  created_at timestamptz NOT NULL DEFAULT now()
);
DO $do$
BEGIN
  IF to_regclass('public.founder_access_denials') IS NOT NULL THEN
    EXECUTE $guard$GRANT ALL ON public.founder_access_denials TO service_role$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF to_regclass('public.founder_access_denials') IS NOT NULL THEN
    EXECUTE $guard$ALTER TABLE public.founder_access_denials ENABLE ROW LEVEL SECURITY$guard$;
  END IF;
END
$do$;

-- ===== from 20261002050331_7ac11e74-e65e-4d5e-9ab7-443ab74e82ce.sql =====
CREATE OR REPLACE FUNCTION private.is_platform_owner()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM auth.users u
    WHERE u.id = auth.uid()
      AND lower(trim(u.email)) = 'rmanish2000@gmail.com'
      AND u.email_confirmed_at IS NOT NULL
  );
$$;
REVOKE EXECUTE ON FUNCTION private.is_platform_owner() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.is_platform_owner() TO authenticated, service_role;

-- ===== PR #5 hardened owner policies on pilot_leads (ensure present) =====
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pilot_leads' AND policyname = 'Platform owner reads pilot applications') THEN
    EXECUTE $guard$CREATE POLICY "Platform owner reads pilot applications" ON public.pilot_leads FOR SELECT TO authenticated USING (private.is_platform_owner())$guard$;
  END IF;
END
$do$;
DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pilot_leads' AND policyname = 'Platform owner updates pilot applications') THEN
    EXECUTE $guard$CREATE POLICY "Platform owner updates pilot applications" ON public.pilot_leads FOR UPDATE TO authenticated USING (private.is_platform_owner()) WITH CHECK (private.is_platform_owner())$guard$;
  END IF;
END
$do$;
