import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Preventive guard: no secret-bearing .env file may ever be committed.
 *
 * The tracked root `.env` is generated by the hosting platform and may hold ONLY
 * public client configuration — the values already shipped to every browser in
 * the client bundle. Privileged credentials belong exclusively in the encrypted
 * backend secret store.
 *
 * This test reads only variable NAMES and value SHAPES; it never prints a value.
 */

const ROOT = resolve(__dirname, "../../..");

/** Keys allowed to appear in a committed .env-style file. */
const PUBLIC_KEYS = new Set([
  "SUPABASE_PROJECT_ID",
  "SUPABASE_URL",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_ANON_KEY",
  "VITE_SUPABASE_PROJECT_ID",
  "VITE_SUPABASE_URL",
  "VITE_SUPABASE_PUBLISHABLE_KEY",
  "VITE_SUPABASE_ANON_KEY",
  "VITE_APP_ENV",
  "APP_ENV",
]);

/** Names that always indicate a privileged credential. */
const FORBIDDEN_KEY_PATTERN =
  /(SERVICE_ROLE|SECRET|PRIVATE|PASSWORD|PASSWD|TOKEN|_PAT\b|CREDENTIAL|SIGNING|WEBHOOK|SMTP|MAIL_|API_KEY)/i;

/** Value shapes that indicate a real credential rather than public config. */
const SECRET_VALUE_PATTERNS: Array<[string, RegExp]> = [
  ["JWT-shaped token", /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}/],
  ["Supabase secret key", /sb_secret_[A-Za-z0-9_-]{8,}/],
  ["OpenAI-style key", /\bsk-[A-Za-z0-9]{16,}/],
  ["Razorpay key", /\brzp_(live|test)_[A-Za-z0-9]{8,}/],
  ["AWS access key id", /\bAKIA[0-9A-Z]{16}\b/],
  ["Google API key", /\bAIza[0-9A-Za-z_-]{20,}/],
  ["Slack token", /\bxox[abprs]-[A-Za-z0-9-]{10,}/],
  ["GitHub token", /\bgh[pousr]_[A-Za-z0-9]{20,}/],
  ["Private key block", /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
  ["Postgres connection string with password", /postgres(ql)?:\/\/[^:\s]+:[^@\s]+@/],
];

function trackedEnvFiles(): string[] {
  try {
    const out = execFileSync("git", ["ls-files"], { cwd: ROOT, encoding: "utf8" });
    return out
      .split("\n")
      .filter((f) => /(^|\/)\.env(\..*)?$/.test(f))
      .filter((f) => !f.endsWith(".example") && !f.endsWith(".sample"))
      .filter((f) => existsSync(resolve(ROOT, f)));
  } catch {
    // Git unavailable (e.g. exported tarball): fall back to the known root file.
    return existsSync(resolve(ROOT, ".env")) ? [".env"] : [];
  }
}

function parseEnv(text: string): Array<{ key: string; value: string }> {
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#") && l.includes("="))
    .map((l) => {
      const i = l.indexOf("=");
      const key = l.slice(0, i).replace(/^export\s+/, "").trim();
      const value = l.slice(i + 1).trim().replace(/^["']|["']$/g, "");
      return { key, value };
    });
}

describe("committed .env files carry no secrets", () => {
  const files = trackedEnvFiles();

  it("only public client configuration keys are committed", () => {
    const offenders: string[] = [];
    for (const file of files) {
      for (const { key } of parseEnv(readFileSync(resolve(ROOT, file), "utf8"))) {
        if (!PUBLIC_KEYS.has(key) || FORBIDDEN_KEY_PATTERN.test(key)) {
          offenders.push(`${file}: ${key}`);
        }
      }
    }
    expect(offenders, `Non-public variable committed (names only): ${offenders.join(", ")}`).toEqual([]);
  });

  it("no committed value has the shape of a real credential", () => {
    const offenders: string[] = [];
    for (const file of files) {
      const text = readFileSync(resolve(ROOT, file), "utf8");
      for (const [label, pattern] of SECRET_VALUE_PATTERNS) {
        if (pattern.test(text)) offenders.push(`${file}: ${label}`);
      }
    }
    expect(offenders, `Secret-shaped value committed: ${offenders.join(", ")}`).toEqual([]);
  });

  it("a redacted .env.example documents the variable names", () => {
    const example = resolve(ROOT, ".env.example");
    expect(existsSync(example)).toBe(true);
    const text = readFileSync(example, "utf8");
    for (const [label, pattern] of SECRET_VALUE_PATTERNS) {
      expect(pattern.test(text), `.env.example contains a ${label}`).toBe(false);
    }
    expect(text).toContain("VITE_SUPABASE_PUBLISHABLE_KEY");
  });

  it("privileged credentials are absent from every tracked env file name set", () => {
    for (const file of files) {
      const keys = parseEnv(readFileSync(resolve(ROOT, file), "utf8")).map((e) => e.key);
      expect(keys.some((k) => /SERVICE_ROLE|KEY_SECRET|WEBHOOK_SECRET/i.test(k))).toBe(false);
    }
  });
});
